//! Generating the sync SQL from source -> target, in the TARGET's dialect.
//!
//! Every destructive statement (DROP …) is only emitted in executable form when `includeDrops = true`;
//! by default they are commented out so a script run by accident deletes nothing. The comments INSIDE the
//! script are written in English: the script is an artifact taken elsewhere, not UI text.

use crate::compare::diff::norm_type;
use crate::compare::ident::{q_ident, q_lit, qualified};
use crate::compare::meta::{ColMeta, FkMeta, IdxMeta, TableMeta};

// ===================== Generating the sync SQL =====================

pub(super) struct SqlOut {
    pub(super) lines: Vec<String>,
    pub(super) include_drops: bool,
}

impl SqlOut {
    pub(super) fn new(include_drops: bool) -> Self {
        SqlOut {
            lines: Vec::new(),
            include_drops,
        }
    }
    pub(super) fn note(&mut self, text: impl AsRef<str>) {
        self.lines.push(format!("-- {}", text.as_ref()));
    }
    pub(super) fn blank(&mut self) {
        self.lines.push(String::new());
    }
    pub(super) fn push(&mut self, stmt: impl Into<String>) {
        self.lines.push(stmt.into());
    }
    /// A destructive statement: only executable when the user enables `includeDrops`.
    pub(super) fn destructive(&mut self, stmt: impl Into<String>) {
        let stmt = stmt.into();
        if self.include_drops {
            self.lines.push(stmt);
        } else {
            self.lines.push(format!("-- {}", stmt));
        }
    }
    /// A DROP + CREATE pair (a changed index/FK). Without `includeDrops`, comment out BOTH,
    /// because running the CREATE on its own would fail on the duplicate name.
    pub(super) fn paired(&mut self, drop_stmt: impl Into<String>, create_stmt: impl Into<String>) {
        self.destructive(drop_stmt);
        self.destructive(create_stmt);
    }
}

/// Renders the source column's default value into the target dialect's SQL.
/// MySQL returns the default as a RAW VALUE (`abc`), Postgres/SQLite return an EXPRESSION
/// (`'abc'::text`), so the source dialect has to be taken into account.
pub(super) fn render_default(src_dialect: &str, tgt_dialect: &str, raw: &str) -> String {
    let trimmed = raw.trim();
    let upper = trimmed.to_ascii_uppercase();
    let is_expr = upper.starts_with("CURRENT_")
        || upper.starts_with("NOW(")
        || upper == "NULL"
        || upper.starts_with("NEXTVAL(")
        || upper.starts_with("UUID(")
        || upper.starts_with("GEN_RANDOM_UUID(")
        || trimmed.parse::<f64>().is_ok();

    if src_dialect == "mysql" {
        if is_expr {
            return trimmed.to_string();
        }
        return q_lit(trimmed);
    }
    // Postgres/SQLite source: already a SQL expression. Drop the `::type` cast when the target is not PG.
    if tgt_dialect != "postgres"
        && let Some(i) = trimmed.find("::")
    {
        return trimmed[..i].trim().to_string();
    }
    trimmed.to_string()
}

/// The clause defining one column, in the TARGET's dialect.
pub(super) fn column_clause(
    c: &ColMeta,
    src_dialect: &str,
    tgt: &str,
    single_int_pk: bool,
) -> String {
    let mut out = format!("{} {}", q_ident(tgt, &c.name), c.data_type);

    if c.auto_increment {
        match tgt {
            "mysql" => out.push_str(" AUTO_INCREMENT"),
            "postgres" => out.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
            "sqlite" if single_int_pk => {
                // SQLite only auto-increments with INTEGER PRIMARY KEY AUTOINCREMENT.
                return format!(
                    "{} INTEGER PRIMARY KEY AUTOINCREMENT",
                    q_ident(tgt, &c.name)
                );
            }
            _ => {}
        }
    }
    if !c.nullable {
        out.push_str(" NOT NULL");
    }
    if let Some(d) = c.default.as_deref().filter(|d| !d.trim().is_empty()) {
        // A default coming from a sequence is already expressed as AUTO_INCREMENT/IDENTITY above.
        if !(c.auto_increment && d.to_ascii_uppercase().contains("NEXTVAL(")) {
            out.push_str(&format!(" DEFAULT {}", render_default(src_dialect, tgt, d)));
        }
    }
    if tgt == "mysql"
        && let Some(cm) = c.comment.as_deref().filter(|c| !c.is_empty())
    {
        out.push_str(&format!(" COMMENT {}", q_lit(cm)));
    }
    out
}

pub(super) fn create_table_sql(
    t: &TableMeta,
    src_dialect: &str,
    tgt: &str,
    schema: &str,
) -> Vec<String> {
    let mut stmts = Vec::new();
    let full = qualified(tgt, schema, &t.name);

    if t.is_view {
        let def = t.view_def.clone().unwrap_or_default();
        if def.trim().is_empty() {
            stmts.push(format!(
                "-- Could not read the definition of view {}",
                t.name
            ));
            return stmts;
        }
        // SQLite stores the whole CREATE VIEW statement in sqlite_master; the other dialects store only the SELECT body.
        let body = def.trim().trim_end_matches(';').to_string();
        if body.to_ascii_uppercase().starts_with("CREATE ") {
            stmts.push(format!("{};", body));
        } else if tgt == "sqlite" {
            stmts.push(format!("CREATE VIEW {} AS {};", full, body));
        } else {
            stmts.push(format!("CREATE OR REPLACE VIEW {} AS {};", full, body));
        }
        return stmts;
    }

    // SQLite -> SQLite: the original CREATE statement is the most complete description (including AUTOINCREMENT,
    // CHECK, inline FKs) and needs no type translation.
    if src_dialect == "sqlite"
        && tgt == "sqlite"
        && let Some(orig) = t.create_sql.as_deref().filter(|s| !s.trim().is_empty())
    {
        stmts.push(format!("{};", orig.trim().trim_end_matches(';')));
        for idx in &t.indexes {
            stmts.push(create_index_sql(idx, &t.name, tgt, schema));
        }
        return stmts;
    }

    let single_int_pk = t.pk.len() == 1
        && t.column(&t.pk[0])
            .map(|c| c.auto_increment || norm_type(&c.data_type).starts_with("int"))
            .unwrap_or(false);

    let mut parts: Vec<String> = t
        .columns
        .iter()
        .map(|c| {
            format!(
                "  {}",
                column_clause(
                    c,
                    src_dialect,
                    tgt,
                    single_int_pk && t.pk.first() == Some(&c.name)
                )
            )
        })
        .collect();

    let inline_pk = !(tgt == "sqlite"
        && single_int_pk
        && t.pk
            .first()
            .map(|p| t.column(p).map(|c| c.auto_increment).unwrap_or(false))
            .unwrap_or(false));
    if !t.pk.is_empty() && inline_pk {
        let cols: Vec<String> = t.pk.iter().map(|c| q_ident(tgt, c)).collect();
        parts.push(format!("  PRIMARY KEY ({})", cols.join(", ")));
    }

    // SQLite has no ALTER TABLE ADD CONSTRAINT -> the FKs have to live inside the CREATE statement.
    if tgt == "sqlite" {
        for fk in &t.fks {
            let cols: Vec<String> = fk.columns.iter().map(|c| q_ident(tgt, c)).collect();
            let refs: Vec<String> = fk.ref_columns.iter().map(|c| q_ident(tgt, c)).collect();
            let mut clause = format!(
                "  FOREIGN KEY ({}) REFERENCES {} ({})",
                cols.join(", "),
                q_ident(tgt, &fk.ref_table),
                refs.join(", ")
            );
            if let Some(rule) = fk
                .on_delete
                .as_deref()
                .filter(|r| !r.is_empty() && !r.eq_ignore_ascii_case("NO ACTION"))
            {
                clause.push_str(&format!(" ON DELETE {}", rule.to_ascii_uppercase()));
            }
            if let Some(rule) = fk
                .on_update
                .as_deref()
                .filter(|r| !r.is_empty() && !r.eq_ignore_ascii_case("NO ACTION"))
            {
                clause.push_str(&format!(" ON UPDATE {}", rule.to_ascii_uppercase()));
            }
            parts.push(clause);
        }
    }

    stmts.push(format!(
        "CREATE TABLE {} (\n{}\n);",
        full,
        parts.join(",\n")
    ));

    for idx in &t.indexes {
        stmts.push(create_index_sql(idx, &t.name, tgt, schema));
    }
    if tgt != "sqlite" {
        for fk in &t.fks {
            stmts.push(add_fk_sql(fk, &t.name, tgt, schema));
        }
    }
    stmts
}

pub(super) fn create_index_sql(idx: &IdxMeta, table: &str, tgt: &str, schema: &str) -> String {
    let cols: Vec<String> = idx
        .columns
        .iter()
        // Postgres allows an index on an expression (`lower(a)`) — leave it alone, do not quote it.
        .map(|c| {
            if c.contains('(') {
                c.clone()
            } else {
                q_ident(tgt, c)
            }
        })
        .collect();
    let unique = if idx.unique { "UNIQUE " } else { "" };
    format!(
        "CREATE {}INDEX {} ON {} ({});",
        unique,
        q_ident(tgt, &idx.name),
        qualified(tgt, schema, table),
        cols.join(", ")
    )
}

pub(super) fn drop_index_sql(idx: &IdxMeta, table: &str, tgt: &str, schema: &str) -> String {
    if tgt == "mysql" {
        format!(
            "DROP INDEX {} ON {};",
            q_ident(tgt, &idx.name),
            qualified(tgt, schema, table)
        )
    } else if tgt == "postgres" {
        format!("DROP INDEX {};", qualified(tgt, schema, &idx.name))
    } else {
        format!("DROP INDEX {};", q_ident(tgt, &idx.name))
    }
}

pub(super) fn add_fk_sql(fk: &FkMeta, table: &str, tgt: &str, schema: &str) -> String {
    let cols: Vec<String> = fk.columns.iter().map(|c| q_ident(tgt, c)).collect();
    let refs: Vec<String> = fk.ref_columns.iter().map(|c| q_ident(tgt, c)).collect();
    let mut sql = format!(
        "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({})",
        qualified(tgt, schema, table),
        q_ident(tgt, &fk.name),
        cols.join(", "),
        qualified(tgt, schema, &fk.ref_table),
        refs.join(", ")
    );
    if let Some(rule) = fk
        .on_delete
        .as_deref()
        .filter(|r| !r.is_empty() && !r.eq_ignore_ascii_case("NO ACTION"))
    {
        sql.push_str(&format!(" ON DELETE {}", rule.to_ascii_uppercase()));
    }
    if let Some(rule) = fk
        .on_update
        .as_deref()
        .filter(|r| !r.is_empty() && !r.eq_ignore_ascii_case("NO ACTION"))
    {
        sql.push_str(&format!(" ON UPDATE {}", rule.to_ascii_uppercase()));
    }
    sql.push(';');
    sql
}

/// SQLite cannot add or drop a foreign key on an existing table (there is no
/// `ALTER TABLE ... ADD/DROP CONSTRAINT`) -> return a note instead of SQL that cannot run.
pub(super) fn fk_stmt_or_note(tgt: &str, table: &str, fk_name: &str, stmt: String) -> String {
    if tgt == "sqlite" {
        format!(
            "-- SQLite cannot add or drop a foreign key on an existing table: {}.{} - recreate the table.",
            table, fk_name
        )
    } else {
        stmt
    }
}

pub(super) fn drop_fk_sql(fk: &FkMeta, table: &str, tgt: &str, schema: &str) -> String {
    let full = qualified(tgt, schema, table);
    if tgt == "mysql" {
        format!(
            "ALTER TABLE {} DROP FOREIGN KEY {};",
            full,
            q_ident(tgt, &fk.name)
        )
    } else {
        format!(
            "ALTER TABLE {} DROP CONSTRAINT {};",
            full,
            q_ident(tgt, &fk.name)
        )
    }
}

/// The statements that change ONE column to match the source. SQLite cannot alter a column -> a note only.
pub(super) fn alter_column_stmts(
    table: &str,
    src: &ColMeta,
    tgt_col: &ColMeta,
    changes: &[&str],
    src_dialect: &str,
    tgt: &str,
    schema: &str,
) -> Vec<String> {
    let full = qualified(tgt, schema, table);
    let mut out = Vec::new();

    match tgt {
        "mysql" => {
            out.push(format!(
                "ALTER TABLE {} MODIFY COLUMN {};",
                full,
                column_clause(src, src_dialect, tgt, false)
            ));
        }
        "postgres" => {
            let col = q_ident(tgt, &src.name);
            if changes.contains(&"type") {
                out.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} TYPE {};",
                    full, col, src.data_type
                ));
            }
            if changes.contains(&"nullable") {
                out.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} {} NOT NULL;",
                    full,
                    col,
                    if src.nullable { "DROP" } else { "SET" }
                ));
            }
            if changes.contains(&"default") {
                match src.default.as_deref().filter(|d| !d.trim().is_empty()) {
                    Some(d) => out.push(format!(
                        "ALTER TABLE {} ALTER COLUMN {} SET DEFAULT {};",
                        full,
                        col,
                        render_default(src_dialect, tgt, d)
                    )),
                    None => out.push(format!(
                        "ALTER TABLE {} ALTER COLUMN {} DROP DEFAULT;",
                        full, col
                    )),
                }
            }
            if changes.contains(&"comment") {
                let cm = src.comment.as_deref().unwrap_or("");
                out.push(format!(
                    "COMMENT ON COLUMN {}.{} IS {};",
                    full,
                    col,
                    if cm.is_empty() {
                        "NULL".to_string()
                    } else {
                        q_lit(cm)
                    }
                ));
            }
        }
        _ => {
            out.push(format!(
                "-- SQLite cannot alter a column: {}.{} ({} -> {}). Recreate the table and copy the data.",
                table, src.name, tgt_col.data_type, src.data_type
            ));
        }
    }
    out
}
