//! The real run: preparing each table, building multi-row INSERTs, writing in batches and committing periodically.
//!
//! One DEDICATED connection for the whole run (`Exec`): `execute_raw_sql_generic` takes a NEW connection
//! from the pool on every call, so `BEGIN` / `SET FOREIGN_KEY_CHECKS` sent through it would land on a
//! different session than the INSERTs.

use std::collections::{HashMap, HashSet};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

use serde_json::{Value, json};
use tauri::ipc::Channel;

use crate::database::{DbConnection, Exec};

use super::column::ColState;
use super::ident::{qualified, quote_ident};
use super::meta::query_rows;
use super::spec::{Cell, GenSpec, GenTableSpec, o_str, opt_i64};

/// Rows per INSERT statement. 500 keeps the statement text far below MySQL's default
/// `max_allowed_packet`, and is dropped further for very wide tables (see `pick_batch_size`).
pub(super) const DEFAULT_BATCH: usize = 500;

/// Parent-key values kept in memory for FK generators that may reference rows created in the
/// same run. A cap is needed because the parent table can itself be a million rows.
pub(super) const FK_POOL_CAP: usize = 100_000;

/// Existing parent rows read to feed a FK generator.
pub(super) const FK_FETCH_LIMIT: usize = 100_000;

/// Distinct values of a parent key, used by the `foreignKey` generator.
pub(super) async fn fetch_fk_pool(
    conn: &DbConnection,
    dialect: &str,
    schema: &Option<String>,
    table: &str,
    column: &str,
) -> Result<Vec<Cell>, String> {
    let sql = format!(
        "SELECT DISTINCT {} AS fkval FROM {} WHERE {} IS NOT NULL LIMIT {}",
        quote_ident(dialect, column),
        qualified(dialect, schema, table),
        quote_ident(dialect, column),
        FK_FETCH_LIMIT
    );
    let rows = query_rows(conn, &sql).await?;
    Ok(rows
        .iter()
        .filter_map(|r| r.get("fkval"))
        .filter(|v| !v.is_null())
        .map(Cell::from_json)
        .collect())
}

/// Keys a parent table is *about to* receive, for the preview only.
///
/// Without this, previewing a child table before its parent has any row shows a column of NULLs —
/// which reads as "the foreign key generator is broken" even though the real run fills it. Two
/// cases, and the second is the common one:
///  - the parent's key is generated by us (sequence/uuid/...): replay that column's generator;

///  - the parent's key is auto-increment (`skip`): only the database knows it, so continue from
///    `MAX(key)` the way the database will.
/// Returns empty when the parent is not part of this run — then there really is nothing to sample.
#[allow(clippy::too_many_arguments)]
pub(super) async fn estimate_fk_pool(
    conn: &DbConnection,
    dialect: &str,
    schema: &Option<String>,
    seed: u64,
    all_tables: &[GenTableSpec],
    ref_table: &str,
    ref_column: &str,
) -> Vec<Cell> {
    // Enough for the preview to look varied without generating a whole parent table.
    const SAMPLE: usize = 200;

    let Some(parent) = all_tables.iter().find(|t| t.table == ref_table) else {
        return Vec::new();
    };
    let want = parent.rows.clamp(1, SAMPLE);

    let parent_col = parent.columns.iter().find(|c| c.column == ref_column);
    if let Some(cspec) = parent_col
        && cspec.generator != "skip"
        && let Ok(mut st) = ColState::new(seed, ref_table, cspec)
    {
        let mut out = Vec::with_capacity(want);
        for _ in 0..want {
            match st.next_cell(dialect) {
                Ok(Cell::Null) => {}
                Ok(cell) => out.push(cell),
                Err(_) => break,
            }
        }
        return out;
    }

    // Auto-increment (or a column left to the database): continue the sequence from MAX(key).
    let sql = format!(
        "SELECT MAX({}) AS mx FROM {}",
        quote_ident(dialect, ref_column),
        qualified(dialect, schema, ref_table)
    );
    let start = query_rows(conn, &sql)
        .await
        .ok()
        .and_then(|rows| rows.first().and_then(|r| opt_i64(r, "mx")))
        .unwrap_or(0);
    (1..=want as i64)
        .map(|i| Cell::Num((start + i).to_string()))
        .collect()
}

pub(super) struct PreparedTable {
    pub(super) columns: Vec<String>,
    pub(super) states: Vec<ColState>,
}

/// Builds the per-column runtime state of one table.
///
/// A FK column draws from the union of two sources, and it needs both:
///  - what the parent table holds (read here) — the only place an auto-increment parent key can
///    come from, since that column is generated by the database, not by us;

///  - `generated`: the key values this run produced for the parent, for the case where the parent
///    is generated *after* the child (a reference cycle) so the table read cannot show them yet.
#[allow(clippy::too_many_arguments)]
pub(super) async fn prepare_table(
    conn: &DbConnection,
    dialect: &str,
    schema: &Option<String>,
    seed: u64,
    tspec: &GenTableSpec,
    // Every table of the run — a preview needs the *parent's* spec to estimate FK values.
    // (A `///` doc comment on a parameter is a compile error, so this stays a plain comment.)
    all_tables: &[GenTableSpec],
    generated: &HashMap<(String, String), Vec<Cell>>,
    warnings: &mut Vec<String>,
    strict_fk: bool,
) -> Result<PreparedTable, String> {
    let mut columns = Vec::new();
    let mut states = Vec::new();
    for cspec in &tspec.columns {
        if cspec.generator == "skip" {
            continue;
        }
        let mut st = ColState::new(seed, &tspec.table, cspec)?;
        if cspec.generator == "foreignKey" {
            let ref_table = o_str(&cspec.options, "refTable").unwrap_or_default();
            let ref_column = o_str(&cspec.options, "refColumn").unwrap_or_default();
            if ref_table.is_empty() || ref_column.is_empty() {
                return Err(format!(
                    "Cột '{}.{}' chưa chọn bảng/cột tham chiếu",
                    tspec.table, cspec.column
                ));
            }
            let mut pool = fetch_fk_pool(conn, dialect, schema, &ref_table, &ref_column).await?;
            if let Some(extra) = generated.get(&(ref_table.clone(), ref_column.clone())) {
                pool.extend(extra.iter().cloned());
            }
            if pool.is_empty() {
                if strict_fk {
                    return Err(format!(
                        "Bảng cha '{}.{}' không có dòng nào để lấy khóa ngoại cho cột '{}.{}'",
                        ref_table, ref_column, tspec.table, cspec.column
                    ));
                }
                // Preview: the parent is still empty, but during the real run it will not be —
                // it is generated first. Showing NULL here would make the feature look broken,
                // so estimate the keys the parent is about to get and say so in a warning.
                pool = estimate_fk_pool(
                    conn,
                    dialect,
                    schema,
                    seed,
                    all_tables,
                    &ref_table,
                    &ref_column,
                )
                .await;
                warnings.push(if pool.is_empty() {
                    format!(
                        "Bảng cha '{}.{}' không có dòng nào để lấy khóa ngoại cho cột '{}.{}'",
                        ref_table, ref_column, tspec.table, cspec.column
                    )
                } else {
                    format!(
                        "Xem trước: khóa ngoại của cột '{}.{}' là ƯỚC LƯỢNG vì bảng cha '{}.{}' còn rỗng; khi sinh thật sẽ lấy khóa thật của bảng cha.",
                        tspec.table, cspec.column, ref_table, ref_column
                    )
                });
            }
            st.pool = pool;
        }
        columns.push(cspec.column.clone());
        states.push(st);
    }
    if states.is_empty() {
        return Err(format!(
            "Bảng '{}' không có cột nào để sinh dữ liệu",
            tspec.table
        ));
    }
    Ok(PreparedTable { columns, states })
}

pub(super) fn insert_sql(
    dialect: &str,
    schema: &Option<String>,
    table: &str,
    columns: &[String],
    rows: &[Vec<Cell>],
) -> String {
    let cols = columns
        .iter()
        .map(|c| quote_ident(dialect, c))
        .collect::<Vec<_>>()
        .join(", ");
    let values = rows
        .iter()
        .map(|row| {
            let cells = row
                .iter()
                .map(|c| c.literal(dialect))
                .collect::<Vec<_>>()
                .join(", ");
            format!("({cells})")
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "INSERT INTO {} ({}) VALUES {};",
        qualified(dialect, schema, table),
        cols,
        values
    )
}

/// Wide tables make the statement text grow fast; keep a batch well under a few MB so a MySQL
/// server with a small `max_allowed_packet` still accepts it.
pub(super) fn pick_batch_size(requested: usize, column_count: usize) -> usize {
    let base = requested.clamp(1, 5_000);
    if column_count > 40 {
        base.min(100)
    } else if column_count > 20 {
        base.min(250)
    } else {
        base
    }
}

#[allow(clippy::too_many_arguments)]
pub(super) async fn run_generation(
    conn: &DbConnection,
    dialect: &str,
    schema: &Option<String>,
    spec: &GenSpec,
    order: &[String],
    seed: u64,
    disable_constraints: bool,
    commit_every: usize,
    remember: &HashSet<(String, String)>,
    total_rows: usize,
    on_progress: &Channel<Value>,
    cancel: &Arc<AtomicBool>,
    warnings: &mut Vec<String>,
) -> Result<(HashMap<String, usize>, bool), String> {
    let mut exec = Exec::acquire(conn).await?;

    // Constraints off, then transaction open. The ORDER is dialect-specific and neither half is
    // interchangeable:
    //  - SQLite: `PRAGMA foreign_keys` is a no-op *inside* a transaction, so it must come first.
    //  - MySQL: `SET FOREIGN_KEY_CHECKS` is session level; before or after works, keep it first.
    //  - Postgres: `SET CONSTRAINTS` is only valid *inside* a transaction, so it comes after
    //    BEGIN — and again after every periodic commit, since it dies with the transaction.
    if disable_constraints {
        match dialect {
            "mysql" => exec.try_run("SET FOREIGN_KEY_CHECKS = 0;").await,
            "postgres" => {}
            _ => exec.try_run("PRAGMA foreign_keys = OFF;").await,
        }
    }
    let begin = if dialect == "mysql" {
        "START TRANSACTION;"
    } else {
        "BEGIN;"
    };
    exec.try_run(begin).await;
    if disable_constraints && dialect == "postgres" {
        exec.try_run("SET CONSTRAINTS ALL DEFERRED;").await;
    }

    let mut inserted: HashMap<String, usize> = HashMap::new();
    let mut generated: HashMap<(String, String), Vec<Cell>> = HashMap::new();
    let mut done_rows = 0usize;
    let mut batches_since_commit = 0usize;
    let mut cancelled = false;

    // A failure must not leave the session with constraints off or a transaction open.
    macro_rules! bail {
        ($msg:expr) => {{
            let msg: String = $msg;
            exec.try_run("ROLLBACK;").await;
            restore_session(&mut exec, dialect, disable_constraints).await;
            return Err(msg);
        }};
    }

    'tables: for table in order {
        let Some(tspec) = spec.tables.iter().find(|t| &t.table == table) else {
            continue;
        };
        if tspec.rows == 0 {
            continue;
        }

        let mut prepared = match prepare_table(
            conn,
            dialect,
            schema,
            seed,
            tspec,
            &spec.tables,
            &generated,
            warnings,
            true,
        )
        .await
        {
            Ok(p) => p,
            Err(e) => bail!(e),
        };

        if tspec.mode.as_deref() == Some("truncate") {
            // DELETE, not TRUNCATE: MySQL implicitly COMMITs on TRUNCATE (DDL), which would
            // make the surrounding transaction unable to roll back what was already written.
            let sql = format!("DELETE FROM {};", qualified(dialect, schema, table));
            if let Err(e) = exec.run(sql).await {
                bail!(format!("Không xoá được dữ liệu cũ của bảng '{table}': {e}"));
            }
        }

        let _ = on_progress.send(json!({
            "type": "table",
            "table": table,
            "rows": tspec.rows,
            "totalDone": done_rows,
            "totalRows": total_rows,
        }));

        let remember_idx: Vec<usize> = prepared
            .columns
            .iter()
            .enumerate()
            .filter(|(_, c)| remember.contains(&(table.clone(), (*c).clone())))
            .map(|(i, _)| i)
            .collect();

        let batch_size = pick_batch_size(
            spec.options
                .as_ref()
                .and_then(|o| o.batch_size)
                .unwrap_or(DEFAULT_BATCH),
            prepared.columns.len(),
        );

        let mut produced = 0usize;
        while produced < tspec.rows {
            if cancel.load(Ordering::Relaxed) {
                cancelled = true;
                break 'tables;
            }
            let take = batch_size.min(tspec.rows - produced);
            let mut rows: Vec<Vec<Cell>> = Vec::with_capacity(take);
            for _ in 0..take {
                let mut row = Vec::with_capacity(prepared.states.len());
                for st in prepared.states.iter_mut() {
                    // The error already names `table.column`, so it needs no wrapper here.
                    match st.next_cell(dialect) {
                        Ok(cell) => row.push(cell),
                        Err(e) => bail!(e),
                    }
                }
                for idx in &remember_idx {
                    let pool = generated
                        .entry((table.clone(), prepared.columns[*idx].clone()))
                        .or_default();
                    if pool.len() < FK_POOL_CAP {
                        pool.push(row[*idx].clone());
                    }
                }
                rows.push(row);
            }

            let sql = insert_sql(dialect, schema, table, &prepared.columns, &rows);
            if let Err(e) = exec.run(sql).await {
                bail!(format!("Lỗi khi chèn dữ liệu vào bảng '{table}': {e}"));
            }

            produced += take;
            done_rows += take;
            *inserted.entry(table.clone()).or_insert(0) += take;
            batches_since_commit += 1;

            let _ = on_progress.send(json!({
                "type": "progress",
                "table": table,
                "done": produced,
                "total": tspec.rows,
                "totalDone": done_rows,
                "totalRows": total_rows,
            }));

            // Periodic commit so a long run does not sit on one giant transaction (undo log /
            // WAL growth), at the cost of a cancel leaving the committed part behind — which is
            // reported back as `inserted`.
            if batches_since_commit >= commit_every {
                exec.try_run("COMMIT;").await;
                exec.try_run(begin).await;
                if disable_constraints && dialect == "postgres" {
                    exec.try_run("SET CONSTRAINTS ALL DEFERRED;").await;
                }
                batches_since_commit = 0;
            }
        }

        // Commit at the end of EVERY table, not just at the end of the run. `prepare_table` reads
        // the parent key of a FK column through `execute_raw_sql_generic`, which takes its own
        // connection from the pool and therefore cannot see rows still uncommitted in ours — the
        // child table would find an empty parent and the whole run would fail. It also is the only
        // way to learn an auto-increment parent key, which the database assigns and we never see.
        // No atomicity is lost that the periodic commit above had not already given up.
        exec.try_run("COMMIT;").await;
        exec.try_run(begin).await;
        if disable_constraints && dialect == "postgres" {
            exec.try_run("SET CONSTRAINTS ALL DEFERRED;").await;
        }
        batches_since_commit = 0;
    }

    exec.try_run("COMMIT;").await;
    restore_session(&mut exec, dialect, disable_constraints).await;
    Ok((inserted, cancelled))
}

/// Puts the session back the way it was before returning the connection to the pool.
pub(super) async fn restore_session(exec: &mut Exec, dialect: &str, disabled: bool) {
    if !disabled {
        return;
    }
    match dialect {
        "mysql" => exec.try_run("SET FOREIGN_KEY_CHECKS = 1;").await,
        "postgres" => {}
        _ => exec.try_run("PRAGMA foreign_keys = ON;").await,
    }
}
