/**
 * ER Diagram Export Helper.
 * Handles exporting ER diagrams into high-resolution PNG, Vector SVG,
 * Mermaid ER Markdown, DBML (dbdiagram.io), and DDL SQL scripts.
 */

import type { ERTable, ERRelationship } from './erTypes';

/**
 * Generates Mermaid ER Diagram markdown string.
 */
export function exportToMermaid(tables: ERTable[], relationships: ERRelationship[]): string {
  const lines: string[] = [];
  lines.push('erDiagram');

  relationships.forEach((rel) => {
    const relName = rel.name ? `"${rel.name}"` : `"${rel.sourceColumn} -> ${rel.targetColumn}"`;
    lines.push(`    ${rel.targetTable} ||--o{ ${rel.sourceTable} : ${relName}`);
  });

  tables.forEach((table) => {
    lines.push(`    ${table.name} {`);
    table.columns.forEach((col) => {
      const cleanType = col.type.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase() || 'text';
      let keyBadge = '';
      if (col.isPrimaryKey && col.isForeignKey) keyBadge = 'PK,FK';
      else if (col.isPrimaryKey) keyBadge = 'PK';
      else if (col.isForeignKey) keyBadge = 'FK';

      lines.push(`        ${cleanType} ${col.name} ${keyBadge}`.trimEnd());
    });
    lines.push('    }');
  });

  return lines.join('\n');
}

function escapeSingleQuote(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Generates DBML (Database Markup Language) format for dbdiagram.io / dbdocs.io.
 */
export function exportToDbml(tables: ERTable[], relationships: ERRelationship[]): string {
  const lines: string[] = [];
  lines.push('// Generated by TableNova ER Visualizer');

  tables.forEach((table) => {
    lines.push(`Table ${table.name} {`);
    table.columns.forEach((col) => {
      const settings: string[] = [];
      if (col.isPrimaryKey) settings.push('pk');
      if (col.nullable === false) settings.push('not null');
      if (col.comment) settings.push(`note: '${escapeSingleQuote(col.comment)}'`);

      const settingStr = settings.length > 0 ? ` [${settings.join(', ')}]` : '';
      lines.push(`  ${col.name} ${col.type}${settingStr}`);
    });
    lines.push('}\n');
  });

  relationships.forEach((rel) => {
    lines.push(`Ref: ${rel.sourceTable}.${rel.sourceColumn} > ${rel.targetTable}.${rel.targetColumn}`);
  });

  return lines.join('\n');
}

/**
 * Generates SQL DDL script sorted by table dependency.
 */
export function exportToSql(tables: ERTable[], relationships: ERRelationship[]): string {
  const lines: string[] = [];
  lines.push('-- ==========================================================');
  lines.push('-- Database Schema DDL Export');
  lines.push(`-- Generated: ${new Date().toLocaleString()}`);
  lines.push('-- ==========================================================\n');

  tables.forEach((table) => {
    lines.push(`CREATE TABLE IF NOT EXISTS \`${table.name}\` (`);
    const colDefs: string[] = [];

    table.columns.forEach((col) => {
      let def = `  \`${col.name}\` ${col.type}`;
      if (col.nullable === false) def += ' NOT NULL';
      if (col.comment) def += ` COMMENT '${escapeSingleQuote(col.comment)}'`;
      colDefs.push(def);
    });

    const pks = table.columns.filter((col) => col.isPrimaryKey).map((col) => `\`${col.name}\``);
    if (pks.length > 0) {
      colDefs.push(`  PRIMARY KEY (${pks.join(', ')})`);
    }

    lines.push(colDefs.join(',\n'));
    lines.push(');\n');
  });

  if (relationships.length > 0) {
    lines.push('-- Foreign Key Constraints');
    relationships.forEach((rel) => {
      const fkName = rel.name || `fk_${rel.sourceTable}_${rel.sourceColumn}`;
      lines.push(
        `ALTER TABLE \`${rel.sourceTable}\` ADD CONSTRAINT \`${fkName}\` FOREIGN KEY (\`${rel.sourceColumn}\`) REFERENCES \`${rel.targetTable}\` (\`${rel.targetColumn}\`);`
      );
    });
  }

  return lines.join('\n');
}

/**
 * Captures diagram SVG and renders into high-res PNG blob and data URL.
 */
export async function captureDiagramToPng(
  svgElement: SVGSVGElement,
  scale: number = 2.0,
  backgroundColor: string = '#0f172a'
): Promise<{ blob: Blob; dataUrl: string }> {
  const svgXml = new XMLSerializer().serializeToString(svgElement);
  const svgBlob = new Blob([svgXml], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);

  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const width = svgElement.clientWidth || 1200;
      const height = svgElement.clientHeight || 800;

      const canvas = document.createElement('canvas');
      canvas.width = width * scale;
      canvas.height = height * scale;

      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error('Failed to get 2D canvas context'));
        return;
      }

      ctx.fillStyle = backgroundColor;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.scale(scale, scale);
      ctx.drawImage(img, 0, 0);

      URL.revokeObjectURL(url);

      const dataUrl = canvas.toDataURL('image/png');
      canvas.toBlob((blob) => {
        if (blob) {
          resolve({ blob, dataUrl });
        } else {
          reject(new Error('Canvas to Blob conversion failed'));
        }
      }, 'image/png');
    };

    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Failed to load SVG image for canvas rendering'));
    };

    img.src = url;
  });
}

/**
 * Downloads a string or blob content as a file.
 */
export function downloadFile(content: string | Blob, fileName: string, mimeType: string) {
  const blob = content instanceof Blob ? content : new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
