import type { DocEntry } from './types';
import { getCommonSqlDocs } from './commonSqlDocs';

export const MYSQL_DOCS: DocEntry[] = [
  ...getCommonSqlDocs('mysql'),
  // --- MySQL 9.x / 8.4 Vector Search Functions ---
  {
    id: 'mysql:vec_distance',
    name: 'VEC_DISTANCE',
    engine: 'mysql',
    category: 'spatial_vector',
    syntax: 'VEC_DISTANCE(vec1, vec2 [, metric])',
    summary: 'Calculates distance between two vector embeddings (MySQL 9.0+ / 8.4+).',
    description: 'Calculates the distance between two vector embeddings. Supported metrics include COSINE, EUCLIDEAN, and DOT product.',
    params: [
      { name: 'vec1', type: 'VECTOR', desc: 'First vector representation or string' },
      { name: 'vec2', type: 'VECTOR', desc: 'Second vector representation or string' },
      { name: 'metric', type: 'VARCHAR', optional: true, desc: "'COSINE' | 'EUCLIDEAN' | 'DOT'" },
    ],
    returns: 'DOUBLE',
    since: 'MySQL 9.0.0 / 8.4.0',
    examples: ["SELECT id, title FROM articles ORDER BY VEC_DISTANCE(embedding, STRING_TO_VECTOR('[0.1, 0.2, 0.3]')) LIMIT 5;"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.4/en/vector-functions.html',
  },
  {
    id: 'mysql:string_to_vector',
    name: 'STRING_TO_VECTOR',
    engine: 'mysql',
    category: 'spatial_vector',
    syntax: "STRING_TO_VECTOR('[val1, val2, ...]')",
    summary: 'Converts a string formatted float array to MySQL binary VECTOR type.',
    description: 'Parses a formatted string representing a floating-point array and converts it to a MySQL binary VECTOR data type.',
    params: [{ name: 'str', type: 'VARCHAR', desc: "Array string like '[0.12, 0.85, 0.44]'" }],
    returns: 'VECTOR',
    since: 'MySQL 9.0.0 / 8.4.0',
    examples: ["SELECT STRING_TO_VECTOR('[0.1, 0.2, 0.3, 0.4]');"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.4/en/vector-functions.html',
  },
  {
    id: 'mysql:vector_to_string',
    name: 'VECTOR_TO_STRING',
    engine: 'mysql',
    category: 'spatial_vector',
    syntax: 'VECTOR_TO_STRING(vector)',
    summary: 'Converts a MySQL binary VECTOR type back into a string array representation.',
    description: 'Converts binary VECTOR data into a human-readable string representation of a floating-point array.',
    params: [{ name: 'vector', type: 'VECTOR', desc: 'Binary VECTOR column or value' }],
    returns: 'VARCHAR',
    since: 'MySQL 9.0.0 / 8.4.0',
    examples: ['SELECT VECTOR_TO_STRING(embedding) FROM document_embeddings;'],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.4/en/vector-functions.html',
  },

  // --- String Functions ---
  {
    id: 'mysql:concat',
    name: 'CONCAT',
    engine: 'mysql',
    category: 'string',
    syntax: 'CONCAT(str1, str2, ...)',
    summary: 'Returns the string that results from concatenating the arguments.',
    description: 'Returns the string that results from concatenating the arguments. May have one or more arguments. If any argument is NULL, CONCAT() returns NULL.',
    params: [{ name: 'str1, str2...', type: 'VARCHAR', desc: 'Strings to concatenate' }],
    returns: 'VARCHAR',
    since: 'MySQL 4.0',
    examples: ["SELECT CONCAT(first_name, ' ', last_name) AS full_name FROM users;"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_concat',
  },
  {
    id: 'mysql:concat_ws',
    name: 'CONCAT_WS',
    engine: 'mysql',
    category: 'string',
    syntax: 'CONCAT_WS(separator, str1, str2, ...)',
    summary: 'Concatenates strings with a specified separator.',
    description: 'CONCAT_WS() stands for Concatenate With Separator and is a special form of CONCAT(). The first argument is the separator for the rest of the arguments.',
    params: [
      { name: 'separator', type: 'VARCHAR', desc: 'Separator string' },
      { name: 'str1, str2...', type: 'VARCHAR', desc: 'Strings to join' },
    ],
    returns: 'VARCHAR',
    since: 'MySQL 4.0.2',
    examples: ["SELECT CONCAT_WS(', ', city, state, country) FROM addresses;"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_concat-ws',
  },
  {
    id: 'mysql:group_concat',
    name: 'GROUP_CONCAT',
    engine: 'mysql',
    category: 'aggregate',
    syntax: 'GROUP_CONCAT([DISTINCT] expr [,expr ...] [ORDER BY ...] [SEPARATOR str_val])',
    summary: 'Returns a concatenated string of non-NULL values from a group.',
    description: 'Returns a string result with the concatenated non-NULL values from a group. Default separator is comma (,).',
    params: [
      { name: 'expr', type: 'VARCHAR', desc: 'Column or expression to aggregate' },
      { name: 'SEPARATOR', type: 'VARCHAR', optional: true, desc: "Custom separator (default ',')" },
    ],
    returns: 'VARCHAR',
    since: 'MySQL 4.1',
    examples: ["SELECT category_id, GROUP_CONCAT(product_name ORDER BY price DESC SEPARATOR '; ') FROM products GROUP BY category_id;"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_group-concat',
  },
  {
    id: 'mysql:regexp_like',
    name: 'REGEXP_LIKE',
    engine: 'mysql',
    category: 'string',
    syntax: 'REGEXP_LIKE(expr, pat [, match_type])',
    summary: 'Returns 1 if string matches regular expression, 0 otherwise.',
    description: 'Performs regular expression matching. Returns 1 if expr matches regular expression pattern pat, 0 otherwise.',
    params: [
      { name: 'expr', type: 'VARCHAR', desc: 'Target string' },
      { name: 'pat', type: 'VARCHAR', desc: 'Regex pattern string' },
      { name: 'match_type', type: 'VARCHAR', optional: true, desc: "'i' (case-insensitive), 'c' (case-sensitive), 'm' (multi-line)" },
    ],
    returns: 'INTEGER',
    since: 'MySQL 8.0.4',
    examples: ["SELECT email FROM users WHERE REGEXP_LIKE(email, '^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$', 'i');"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/regexp.html#function_regexp-like',
  },
  {
    id: 'mysql:regexp_replace',
    name: 'REGEXP_REPLACE',
    engine: 'mysql',
    category: 'string',
    syntax: 'REGEXP_REPLACE(expr, pat, repl [, pos [, occurrence [, match_type]]])',
    summary: 'Replaces occurrences matching regular expression pattern.',
    description: 'Replaces occurrences in expr that match regular expression pattern pat with replacement string repl.',
    params: [
      { name: 'expr', type: 'VARCHAR', desc: 'Input text string' },
      { name: 'pat', type: 'VARCHAR', desc: 'Regex pattern' },
      { name: 'repl', type: 'VARCHAR', desc: 'Replacement string' },
    ],
    returns: 'VARCHAR',
    since: 'MySQL 8.0.4',
    examples: ["SELECT REGEXP_REPLACE('cat shirt fat cat', 'cat', 'dog');"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/regexp.html#function_regexp-replace',
  },

  // --- Date & Time Functions ---
  {
    id: 'mysql:now',
    name: 'NOW',
    engine: 'mysql',
    category: 'datetime',
    syntax: 'NOW([fsp])',
    summary: 'Returns current date and time in YYYY-MM-DD HH:MM:SS format.',
    description: 'Returns the current date and time as a value in YYYY-MM-DD HH:MM:SS or YYYYMMDDHHMMSS format, depending on context.',
    params: [{ name: 'fsp', type: 'INTEGER', optional: true, desc: 'Fractional seconds precision (0-6)' }],
    returns: 'DATETIME',
    since: 'MySQL 4.0',
    examples: ['SELECT NOW(); -- Current datetime', 'SELECT NOW(3); -- With milliseconds'],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_now',
  },
  {
    id: 'mysql:date_add',
    name: 'DATE_ADD',
    engine: 'mysql',
    category: 'datetime',
    syntax: 'DATE_ADD(date, INTERVAL expr unit)',
    summary: 'Adds a time interval to a date value.',
    description: 'Performs date arithmetic. The unit argument indicates the unit for expr (DAY, MONTH, YEAR, HOUR, MINUTE, SECOND, WEEK).',
    params: [
      { name: 'date', type: 'DATETIME | DATE', desc: 'Starting date/datetime' },
      { name: 'expr', type: 'INTEGER', desc: 'Amount of interval to add' },
      { name: 'unit', type: 'KEYWORD', desc: 'DAY | MONTH | YEAR | HOUR | MINUTE | SECOND' },
    ],
    returns: 'DATETIME',
    since: 'MySQL 3.23',
    examples: ['SELECT DATE_ADD(NOW(), INTERVAL 7 DAY);', "SELECT DATE_ADD('2026-01-01', INTERVAL 1 MONTH);"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-add',
  },
  {
    id: 'mysql:date_format',
    name: 'DATE_FORMAT',
    engine: 'mysql',
    category: 'datetime',
    syntax: 'DATE_FORMAT(date, format)',
    summary: 'Formats a date value according to format string.',
    description: 'Formats date value according to specifiers (%Y, %m, %d, %H, %i, %s, %W, %M).',
    params: [
      { name: 'date', type: 'DATETIME', desc: 'Date/datetime value' },
      { name: 'format', type: 'VARCHAR', desc: "Format specifier string like '%Y-%m-%d %H:%i:%s'" },
    ],
    returns: 'VARCHAR',
    since: 'MySQL 3.23',
    examples: ["SELECT DATE_FORMAT(NOW(), '%W, %M %e, %Y');"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-format',
  },

  // --- JSON Functions (MySQL 8.0 / 8.4 / 9.0) ---
  {
    id: 'mysql:json_extract',
    name: 'JSON_EXTRACT',
    engine: 'mysql',
    category: 'json',
    syntax: 'JSON_EXTRACT(json_doc, path[, path]...)',
    summary: 'Extracts data from JSON document matching path(s).',
    description: 'Returns data from a JSON document matching path expressions. Operator shortcut is json_doc->path or json_doc->>path.',
    params: [
      { name: 'json_doc', type: 'JSON', desc: 'JSON column or JSON document' },
      { name: 'path', type: 'VARCHAR', desc: "JSON path like '$.user.id' or '$[0]'" },
    ],
    returns: 'JSON',
    since: 'MySQL 5.7.8 / 8.0',
    examples: ["SELECT JSON_EXTRACT('{\"id\": 10, \"name\": \"TableGrid\"}', '$.name');", "SELECT data->>'$.email' FROM user_profiles;"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-extract',
  },
  {
    id: 'mysql:json_arrayagg',
    name: 'JSON_ARRAYAGG',
    engine: 'mysql',
    category: 'json',
    syntax: 'JSON_ARRAYAGG(col)',
    summary: 'Aggregates a result set column as a JSON array.',
    description: 'Aggregates a result set column into a single JSON array containing all non-NULL values from grouped rows.',
    params: [{ name: 'col', type: 'ANY', desc: 'Column to aggregate' }],
    returns: 'JSON',
    since: 'MySQL 5.7.22 / 8.0',
    examples: ['SELECT department_id, JSON_ARRAYAGG(name) FROM employees GROUP BY department_id;'],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_json-arrayagg',
  },
  {
    id: 'mysql:json_objectagg',
    name: 'JSON_OBJECTAGG',
    engine: 'mysql',
    category: 'json',
    syntax: 'JSON_OBJECTAGG(key_col, val_col)',
    summary: 'Aggregates key/value column pairs into a JSON object.',
    description: 'Takes key and value column expressions and returns a JSON object containing key-value pairs aggregated from the result set.',
    params: [
      { name: 'key_col', type: 'VARCHAR', desc: 'Key column' },
      { name: 'val_col', type: 'ANY', desc: 'Value column' },
    ],
    returns: 'JSON',
    since: 'MySQL 5.7.22 / 8.0',
    examples: ['SELECT JSON_OBJECTAGG(config_key, config_val) FROM app_settings;'],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_json-objectagg',
  },

  // --- Control Flow ---
  {
    id: 'mysql:ifnull',
    name: 'IFNULL',
    engine: 'mysql',
    category: 'control_flow',
    syntax: 'IFNULL(expr1, expr2)',
    summary: 'Returns expr1 if not NULL, else expr2.',
    description: 'If expr1 is not NULL, IFNULL() returns expr1; otherwise it returns expr2.',
    params: [
      { name: 'expr1', type: 'ANY', desc: 'First candidate expression' },
      { name: 'expr2', type: 'ANY', desc: 'Fallback expression' },
    ],
    returns: 'ANY',
    since: 'MySQL 3.23',
    examples: ["SELECT IFNULL(phone, 'No Phone') FROM contacts;"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/flow-control-functions.html#function_ifnull',
  },
  {
    id: 'mysql:coalesce',
    name: 'COALESCE',
    engine: 'mysql',
    category: 'control_flow',
    syntax: 'COALESCE(value1, value2, ...)',
    summary: 'Returns the first non-NULL value in list.',
    description: 'Returns the first non-NULL value in the list, or NULL if all values are NULL.',
    params: [{ name: 'value1, value2...', type: 'ANY', desc: 'List of expressions' }],
    returns: 'ANY',
    since: 'MySQL 3.23',
    examples: ["SELECT COALESCE(work_phone, mobile_phone, home_phone, 'N/A') FROM users;"],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/flow-control-functions.html#function_coalesce',
  },

  // --- Window Functions ---
  {
    id: 'mysql:row_number',
    name: 'ROW_NUMBER',
    engine: 'mysql',
    category: 'window',
    syntax: 'ROW_NUMBER() OVER ([PARTITION BY ...] ORDER BY ...)',
    summary: 'Returns sequential row index within window partition.',
    description: 'Returns the number of the current row within its partition, counting from 1.',
    params: [],
    returns: 'BIGINT',
    since: 'MySQL 8.0.2',
    examples: ['SELECT name, department, ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS rn FROM employees;'],
    officialUrl: 'https://dev.mysql.com/doc/refman/8.0/en/window-function-descriptions.html#function_row-number',
  },
];
