import type { DocEntry } from './types';
import { getCommonSqlDocs } from './commonSqlDocs';

export const POSTGRES_DOCS: DocEntry[] = [
  ...getCommonSqlDocs('postgres'),
  // --- PostgreSQL 17 / 18 JSON_TABLE & pgvector ---
  {
    id: 'postgres:json_table',
    name: 'JSON_TABLE',
    engine: 'postgres',
    category: 'json',
    syntax: 'JSON_TABLE(context_item, path_expression PASSING ... COLUMNS (...))',
    summary: 'Queries JSON data and presents it as a relational table (PG 17+ / 18+).',
    description: 'Maps JSON document elements into relational columns with explicit data types, default fallbacks, and nested path expressions.',
    params: [
      { name: 'context_item', type: 'jsonb | json', desc: 'Input JSON/JSONB document' },
      { name: 'path_expression', type: 'text', desc: "JSON path like '$[*]' or '$.orders[*]'" },
    ],
    returns: 'TABLE',
    since: 'PostgreSQL 17 / 18',
    examples: [
      "SELECT * FROM JSON_TABLE('{\"users\": [{\"id\": 1, \"name\": \"Alice\"}, {\"id\": 2, \"name\": \"Bob\"}]}', '$.users[*]' COLUMNS (id INT PATH '$.id', name TEXT PATH '$.name')) AS jt;",
    ],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-TABLE',
  },
  {
    id: 'postgres:cosine_distance',
    name: 'COSINE_DISTANCE',
    engine: 'postgres',
    category: 'spatial_vector',
    syntax: 'vec1 <=> vec2',
    summary: 'Calculates cosine distance between two pgvector embeddings (<=> operator).',
    description: 'Calculates cosine distance between two vectors using the pgvector extension operator <=> (cosine distance = 1 - cosine similarity).',
    params: [
      { name: 'vec1', type: 'vector', desc: 'First vector' },
      { name: 'vec2', type: 'vector', desc: 'Second vector' },
    ],
    returns: 'double precision',
    since: 'pgvector / PG 15+',
    examples: ["SELECT id, title FROM items ORDER BY embedding <=> '[0.1, 0.2, 0.3]' LIMIT 5;"],
    officialUrl: 'https://github.com/pgvector/pgvector',
  },

  // --- JSONB Functions ---
  {
    id: 'postgres:jsonb_build_object',
    name: 'JSONB_BUILD_OBJECT',
    engine: 'postgres',
    category: 'json',
    syntax: 'jsonb_build_object(key1, val1, key2, val2, ...)',
    summary: 'Builds a JSONB object from a variadic argument list.',
    description: 'Builds a JSONB object from a variadic argument list of alternating keys and values. Keys are coerced to text.',
    params: [
      { name: 'key', type: 'text', desc: 'Property key' },
      { name: 'value', type: 'any', desc: 'Property value' },
    ],
    returns: 'jsonb',
    since: 'PostgreSQL 9.4',
    examples: ["SELECT jsonb_build_object('id', user_id, 'name', first_name || ' ' || last_name) FROM users;"],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-CREATION-TABLE',
  },
  {
    id: 'postgres:jsonb_pretty',
    name: 'JSONB_PRETTY',
    engine: 'postgres',
    category: 'json',
    syntax: 'jsonb_pretty(jsonb)',
    summary: 'Formats JSONB as an indented, human-readable string.',
    description: 'Returns given JSONB value formatted as an indented JSON string with line breaks.',
    params: [{ name: 'jsonb', type: 'jsonb', desc: 'Target JSONB object or array' }],
    returns: 'text',
    since: 'PostgreSQL 9.5',
    examples: ["SELECT jsonb_pretty('{\"id\": 1, \"roles\": [\"admin\", \"dev\"]}'::jsonb);"],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-json.html',
  },
  {
    id: 'postgres:jsonb_set',
    name: 'JSONB_SET',
    engine: 'postgres',
    category: 'json',
    syntax: 'jsonb_set(target jsonb, path text[], new_value jsonb [, create_if_missing boolean])',
    summary: 'Replaces or inserts a JSONB value at target path.',
    description: 'Returns target with the item designated by path replaced by new_value, or with new_value added if create_if_missing is true (default).',
    params: [
      { name: 'target', type: 'jsonb', desc: 'Source JSONB document' },
      { name: 'path', type: 'text[]', desc: "Path array like '{user, name}'" },
      { name: 'new_value', type: 'jsonb', desc: 'Replacement JSONB value' },
      { name: 'create_if_missing', type: 'boolean', optional: true, desc: 'Add field if not found (default true)' },
    ],
    returns: 'jsonb',
    since: 'PostgreSQL 9.5',
    examples: ["SELECT jsonb_set('{\"user\": {\"name\": \"Alice\"}}'::jsonb, '{user, name}', '\"Bob\"'::jsonb);"],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-PROCESSING-TABLE',
  },

  // --- Date & Time Functions ---
  {
    id: 'postgres:date_trunc',
    name: 'DATE_TRUNC',
    engine: 'postgres',
    category: 'datetime',
    syntax: "date_trunc(field, source [, time_zone])",
    summary: 'Truncates a timestamp to specified precision.',
    description: "Truncates timestamp or interval to specified precision field ('microseconds', 'milliseconds', 'second', 'minute', 'hour', 'day', 'week', 'month', 'quarter', 'year').",
    params: [
      { name: 'field', type: 'text', desc: "Field string like 'day', 'month', 'year'" },
      { name: 'source', type: 'timestamp | timestamptz', desc: 'Timestamp value' },
    ],
    returns: 'timestamp / timestamptz',
    since: 'PostgreSQL 7.0',
    examples: ["SELECT date_trunc('month', now()); -- First day of current month"],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC',
  },
  {
    id: 'postgres:to_char',
    name: 'TO_CHAR',
    engine: 'postgres',
    category: 'datetime',
    syntax: 'to_char(timestamp, format)',
    summary: 'Converts timestamp or number to formatted text string.',
    description: "Formats timestamp, interval, integer, or floating-point value to string according to format pattern ('YYYY-MM-DD HH24:MI:SS').",
    params: [
      { name: 'timestamp', type: 'timestamp | numeric', desc: 'Input timestamp or number' },
      { name: 'format', type: 'text', desc: "Format pattern like 'YYYY-MM-DD HH24:MI:SS'" },
    ],
    returns: 'text',
    since: 'PostgreSQL 7.0',
    examples: ["SELECT to_char(now(), 'YYYY-MM-DD HH24:MI:SS');"],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-formatting.html',
  },

  // --- Aggregate Functions ---
  {
    id: 'postgres:string_agg',
    name: 'STRING_AGG',
    engine: 'postgres',
    category: 'aggregate',
    syntax: 'string_agg(expression, delimiter [ORDER BY ...])',
    summary: 'Concatenates non-null input values into a string separated by delimiter.',
    description: 'Concatenates input values into a string, separated by delimiter string.',
    params: [
      { name: 'expression', type: 'text', desc: 'Input expression to join' },
      { name: 'delimiter', type: 'text', desc: 'Delimiter string' },
    ],
    returns: 'text',
    since: 'PostgreSQL 9.0',
    examples: ["SELECT dept_id, string_agg(emp_name, ', ' ORDER BY emp_name) FROM employees GROUP BY dept_id;"],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-aggregate.html',
  },
  {
    id: 'postgres:array_agg',
    name: 'ARRAY_AGG',
    engine: 'postgres',
    category: 'aggregate',
    syntax: 'array_agg(expression [ORDER BY ...])',
    summary: 'Input values, including nulls, aggregated into an array.',
    description: 'Aggregates values into a PostgreSQL array.',
    params: [{ name: 'expression', type: 'anyelement', desc: 'Column or value expression' }],
    returns: 'anyarray',
    since: 'PostgreSQL 8.4',
    examples: ['SELECT dept_id, array_agg(emp_name ORDER BY salary DESC) FROM employees GROUP BY dept_id;'],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-aggregate.html',
  },

  // --- Control Flow ---
  {
    id: 'postgres:coalesce',
    name: 'COALESCE',
    engine: 'postgres',
    category: 'control_flow',
    syntax: 'coalesce(value [, ...])',
    summary: 'Returns the first of its arguments that is not null.',
    description: 'Returns the first non-null argument. Null is returned only if all arguments are null.',
    params: [{ name: 'value', type: 'any', desc: 'Candidate expressions' }],
    returns: 'any',
    since: 'PostgreSQL 6.5',
    examples: ["SELECT coalesce(nickname, first_name, 'Anonymous') FROM profiles;"],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL',
  },

  // --- Window Functions ---
  {
    id: 'postgres:row_number',
    name: 'ROW_NUMBER',
    engine: 'postgres',
    category: 'window',
    syntax: 'row_number() OVER ([PARTITION BY ...] ORDER BY ...)',
    summary: 'Number of the current row within its partition, counting from 1.',
    description: 'Returns sequential 1-based index of current row within window partition.',
    params: [],
    returns: 'bigint',
    since: 'PostgreSQL 8.4',
    examples: ['SELECT name, salary, row_number() OVER (PARTITION BY dept ORDER BY salary DESC) FROM staff;'],
    officialUrl: 'https://www.postgresql.org/docs/current/functions-window.html',
  },
];
