import type { DocEntry } from './types';

export const REDIS_DOCS: DocEntry[] = [
  // --- Redis 8.0+ Vector & Search Commands ---
  {
    id: 'redis:ft.search',
    name: 'FT.SEARCH',
    engine: 'redis',
    category: 'command',
    syntax: 'FT.SEARCH index query [NOCONTENT] [LIMIT offset num] [PARAMS nargs name val...]',
    summary: 'Executes full-text or vector search query against search index (Redis 8.0+ / RediSearch).',
    description: 'Searches the index with a query expression, returning documents matching text filter or vector similarity KNN search.',
    params: [
      { name: 'index', type: 'string', desc: 'Target index name' },
      { name: 'query', type: 'string', desc: "Query string e.g. '*=>[KNN 5 @vector $vec]'" },
    ],
    complexity: 'O(N) for full scan, O(K log N) for vector KNN index search',
    since: 'Redis 8.0 / RediSearch 2.0',
    examples: ['FT.SEARCH idx:books "technology" LIMIT 0 10', "FT.SEARCH idx:docs '*=>[KNN 3 @vec $query_vec]' PARAMS 2 query_vec \"\\x00...\" DIALECT 2"],
    officialUrl: 'https://redis.io/commands/ft.search/',
  },

  // --- Redis JSON Commands ---
  {
    id: 'redis:json.set',
    name: 'JSON.SET',
    engine: 'redis',
    category: 'command',
    syntax: 'JSON.SET key path value [NX | XX]',
    summary: 'Sets the JSON value at path in key (Redis 8.0+ / RedisJSON).',
    description: 'Sets the JSON value at path in key. Path $ represents the root document.',
    params: [
      { name: 'key', type: 'string', desc: 'Target key name' },
      { name: 'path', type: 'string', desc: "JSON path e.g. '$' or '$.user.name'" },
      { name: 'value', type: 'json', desc: 'Valid JSON string' },
    ],
    complexity: 'O(M+N) where M is size of original value and N is size of new value',
    since: 'Redis 8.0 / RedisJSON 1.0',
    examples: ['JSON.SET user:100 $ \'{"name":"Alice","role":"admin"}\''],
    officialUrl: 'https://redis.io/commands/json.set/',
  },
  {
    id: 'redis:json.get',
    name: 'JSON.GET',
    engine: 'redis',
    category: 'command',
    syntax: 'JSON.GET key [INDENT indentation] [NEWLINE line-break] [SPACE space] [path ...]',
    summary: 'Gets the JSON value at path from key.',
    description: 'Returns the value at path in JSON format.',
    params: [
      { name: 'key', type: 'string', desc: 'Target key' },
      { name: 'path', type: 'string', optional: true, desc: "JSON path e.g. '$'" },
    ],
    complexity: 'O(N) where N is size of JSON object',
    since: 'Redis 8.0 / RedisJSON 1.0',
    examples: ['JSON.GET user:100 $', 'JSON.GET user:100 $.name'],
    officialUrl: 'https://redis.io/commands/json.get/',
  },

  // --- String Commands ---
  {
    id: 'redis:get',
    name: 'GET',
    engine: 'redis',
    category: 'command',
    syntax: 'GET key',
    summary: 'Get the value of a key.',
    description: 'Get the value of key. If the key does not exist the special value nil is returned. An error is returned if the value stored at key is not a string.',
    params: [{ name: 'key', type: 'string', desc: 'Target key name' }],
    complexity: 'O(1)',
    since: 'Redis 1.0.0',
    examples: ['GET mykey', 'GET session:token:89a12'],
    officialUrl: 'https://redis.io/commands/get/',
  },
  {
    id: 'redis:set',
    name: 'SET',
    engine: 'redis',
    category: 'command',
    syntax: 'SET key value [NX | XX] [GET] [EX seconds | PX milliseconds | EXAT timestamp | PXAT timestamp | KEEPTTL]',
    summary: 'Set the string value of a key.',
    description: 'Set key to hold the string value. If key already holds a value, it is overwritten, regardless of its type. Options allow setting TTL or conditional overwrite (NX/XX).',
    params: [
      { name: 'key', type: 'string', desc: 'Target key name' },
      { name: 'value', type: 'string', desc: 'String or binary value' },
      { name: 'EX', type: 'seconds', optional: true, desc: 'Set expiration in seconds' },
      { name: 'NX', type: 'flag', optional: true, desc: 'Only set key if it does not already exist' },
    ],
    complexity: 'O(1)',
    since: 'Redis 1.0.0',
    examples: ['SET mykey "Hello World"', 'SET lock:order:100 "active" EX 30 NX'],
    officialUrl: 'https://redis.io/commands/set/',
  },
  {
    id: 'redis:incr',
    name: 'INCR',
    engine: 'redis',
    category: 'command',
    syntax: 'INCR key',
    summary: 'Increments the integer value of a key by one.',
    description: 'Increments the number stored at key by one. If the key does not exist, it is set to 0 before performing the operation.',
    params: [{ name: 'key', type: 'string', desc: 'Counter key' }],
    complexity: 'O(1)',
    since: 'Redis 1.0.0',
    examples: ['INCR page_views:home'],
    officialUrl: 'https://redis.io/commands/incr/',
  },

  // --- Hash Commands ---
  {
    id: 'redis:hset',
    name: 'HSET',
    engine: 'redis',
    category: 'command',
    syntax: 'HSET key field value [field value ...]',
    summary: 'Sets field values in a hash stored at key.',
    description: 'Sets the specified fields to their respective values in the hash stored at key.',
    params: [
      { name: 'key', type: 'string', desc: 'Hash key name' },
      { name: 'field', type: 'string', desc: 'Field name' },
      { name: 'value', type: 'string', desc: 'Field value' },
    ],
    complexity: 'O(1) for each field/value pair added',
    since: 'Redis 2.0.0',
    examples: ['HSET user:1000 name "Alice" email "alice@example.com" age "30"'],
    officialUrl: 'https://redis.io/commands/hset/',
  },
  {
    id: 'redis:hgetall',
    name: 'HGETALL',
    engine: 'redis',
    category: 'command',
    syntax: 'HGETALL key',
    summary: 'Gets all fields and values of a hash.',
    description: 'Returns all fields and values of the hash stored at key.',
    params: [{ name: 'key', type: 'string', desc: 'Hash key name' }],
    complexity: 'O(N) where N is the size of the hash',
    since: 'Redis 2.0.0',
    examples: ['HGETALL user:1000'],
    officialUrl: 'https://redis.io/commands/hgetall/',
  },

  // --- List Commands ---
  {
    id: 'redis:lpush',
    name: 'LPUSH',
    engine: 'redis',
    category: 'command',
    syntax: 'LPUSH key element [element ...]',
    summary: 'Prepend one or multiple elements to a list.',
    description: 'Insert all specified values at the head of the list stored at key. Created if key does not exist.',
    params: [
      { name: 'key', type: 'string', desc: 'List key' },
      { name: 'element', type: 'string', desc: 'Element value(s)' },
    ],
    complexity: 'O(1) for each element added',
    since: 'Redis 1.0.0',
    examples: ['LPUSH queue:tasks "task1" "task2"'],
    officialUrl: 'https://redis.io/commands/lpush/',
  },
  {
    id: 'redis:rpop',
    name: 'RPOP',
    engine: 'redis',
    category: 'command',
    syntax: 'RPOP key [count]',
    summary: 'Remove and get the last element(s) in a list.',
    description: 'Removes and returns the last element of the list stored at key.',
    params: [{ name: 'key', type: 'string', desc: 'List key' }],
    complexity: 'O(1)',
    since: 'Redis 1.0.0',
    examples: ['RPOP queue:tasks'],
    officialUrl: 'https://redis.io/commands/rpop/',
  },

  // --- Set & Sorted Set Commands ---
  {
    id: 'redis:zadd',
    name: 'ZADD',
    engine: 'redis',
    category: 'command',
    syntax: 'ZADD key [NX | XX] [GT | LT] [CH] [INCR] score member [score member ...]',
    summary: 'Add one or more members to a sorted set, or update its score if it already exists.',
    description: 'Adds all specified members with specified scores to the sorted set stored at key.',
    params: [
      { name: 'key', type: 'string', desc: 'Sorted set key' },
      { name: 'score', type: 'double', desc: 'Numerical ordering score' },
      { name: 'member', type: 'string', desc: 'Member string' },
    ],
    complexity: 'O(M*log(N)) where M is number of added members and N is total elements in sorted set',
    since: 'Redis 1.2.0',
    examples: ['ZADD leaderboard 100 "Alice" 150 "Bob" 85 "Charlie"'],
    officialUrl: 'https://redis.io/commands/zadd/',
  },

  // --- Stream Commands ---
  {
    id: 'redis:xadd',
    name: 'XADD',
    engine: 'redis',
    category: 'command',
    syntax: 'XADD key [NOMKSTREAM] [MAXLEN | MINID [~ | =] threshold] id field value [field value ...]',
    summary: 'Appends a new entry to a stream.',
    description: 'Appends specified stream entry to the stream stored at key. * auto-generates ID.',
    params: [
      { name: 'key', type: 'string', desc: 'Stream key' },
      { name: 'id', type: 'string', desc: "Entry ID like '*' or timestamp-seq" },
      { name: 'field', type: 'string', desc: 'Field name' },
      { name: 'value', type: 'string', desc: 'Field value' },
    ],
    complexity: 'O(1) for adding entry',
    since: 'Redis 5.0.0',
    examples: ["XADD mystream * sensor_id 12 temperature 19.8", "XADD mystream MAXLEN ~ 1000 * event \"login\""],
    officialUrl: 'https://redis.io/commands/xadd/',
  },
  {
    id: 'redis:xreadgroup',
    name: 'XREADGROUP',
    engine: 'redis',
    category: 'command',
    syntax: 'XREADGROUP GROUP group consumer [COUNT count] [BLOCK milliseconds] [NOACK] STREAMS key... id...',
    summary: 'Reads entries from a stream using a consumer group.',
    description: 'Special version of XREAD supporting consumer groups for distributed work assignment.',
    params: [
      { name: 'group', type: 'string', desc: 'Consumer group name' },
      { name: 'consumer', type: 'string', desc: 'Consumer worker identifier' },
    ],
    complexity: 'O(M) where M is number of elements returned',
    since: 'Redis 5.0.0',
    examples: ['XREADGROUP GROUP mygroup consumer1 COUNT 10 STREAMS mystream >'],
    officialUrl: 'https://redis.io/commands/xreadgroup/',
  },
];
