import type { DocEntry } from './types';
import { getCommonSqlDocs } from './commonSqlDocs';

export const SQLITE_DOCS: DocEntry[] = [
  ...getCommonSqlDocs('sqlite'),
  // --- String Functions ---
  {
    id: 'sqlite:abs',
    name: 'ABS',
    engine: 'sqlite',
    category: 'math',
    syntax: 'ABS(X)',
    summary: 'Returns the absolute value of numerical argument X.',
    description: 'Returns the absolute value of the numeric argument X. If X is NULL, ABS(X) returns NULL. If X is a string or blob that cannot be converted to a numeric value, ABS(X) returns 0.0.',
    params: [{ name: 'X', type: 'numeric', desc: 'Input number' }],
    returns: 'numeric',
    since: 'SQLite 3.0',
    examples: ['SELECT ABS(-42); -- Returns 42', 'SELECT ABS(val) FROM measurements;'],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#abs',
  },
  {
    id: 'sqlite:coalesce',
    name: 'COALESCE',
    engine: 'sqlite',
    category: 'control_flow',
    syntax: 'COALESCE(X, Y, ...)',
    summary: 'Returns a copy of its first non-NULL argument.',
    description: 'Returns a copy of its first non-NULL argument, or NULL if all arguments are NULL. COALESCE() requires at least 2 arguments.',
    params: [
      { name: 'X', type: 'any', desc: 'First candidate value' },
      { name: 'Y', type: 'any', desc: 'Fallback candidate value' },
    ],
    returns: 'any',
    since: 'SQLite 3.0',
    examples: ["SELECT COALESCE(phone, mobile, 'N/A') FROM contacts;"],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#coalesce',
  },
  {
    id: 'sqlite:concat',
    name: 'CONCAT',
    engine: 'sqlite',
    category: 'string',
    syntax: 'CONCAT(X, Y, ...)',
    summary: 'Concatenates all non-NULL arguments into a single string.',
    description: 'Returns a string formed by concatenating all non-NULL arguments. NULL arguments are ignored. If all arguments are NULL, CONCAT returns an empty string.',
    params: [{ name: '...', type: 'text', desc: 'Strings to concatenate' }],
    returns: 'text',
    since: 'SQLite 3.44.0',
    examples: ["SELECT CONCAT(first_name, ' ', last_name) AS full_name FROM users;"],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#concat',
  },
  {
    id: 'sqlite:length',
    name: 'LENGTH',
    engine: 'sqlite',
    category: 'string',
    syntax: 'LENGTH(X)',
    summary: 'Returns the string length or blob size in bytes.',
    description: 'For a string value X, LENGTH(X) returns the number of characters prior to the first NUL character. For a BLOB value, LENGTH(X) returns the number of bytes.',
    params: [{ name: 'X', type: 'text | blob', desc: 'String or BLOB expression' }],
    returns: 'integer',
    since: 'SQLite 3.0',
    examples: ["SELECT LENGTH('TableNova'); -- Returns 9"],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#length',
  },
  {
    id: 'sqlite:lower',
    name: 'LOWER',
    engine: 'sqlite',
    category: 'string',
    syntax: 'LOWER(X)',
    summary: 'Converts an ASCII string to lower-case.',
    description: 'Returns a copy of string X with all ASCII characters converted to lower-case.',
    params: [{ name: 'X', type: 'text', desc: 'Input string' }],
    returns: 'text',
    since: 'SQLite 3.0',
    examples: ["SELECT LOWER('SQLite DB'); -- Returns 'sqlite db'"],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#lower',
  },
  {
    id: 'sqlite:upper',
    name: 'UPPER',
    engine: 'sqlite',
    category: 'string',
    syntax: 'UPPER(X)',
    summary: 'Converts an ASCII string to upper-case.',
    description: 'Returns a copy of string X with all ASCII characters converted to upper-case.',
    params: [{ name: 'X', type: 'text', desc: 'Input string' }],
    returns: 'text',
    since: 'SQLite 3.0',
    examples: ["SELECT UPPER('sqlite'); -- Returns 'SQLITE'"],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#upper',
  },
  {
    id: 'sqlite:substr',
    name: 'SUBSTR',
    engine: 'sqlite',
    category: 'string',
    syntax: 'SUBSTR(X, Y, Z)',
    summary: 'Extracts a substring starting at character Y with length Z.',
    description: 'Returns a substring of string X starting at 1-based character position Y and continuing for Z characters. If Z is omitted, all remaining characters are returned.',
    params: [
      { name: 'X', type: 'text', desc: 'Input string' },
      { name: 'Y', type: 'integer', desc: '1-based starting character position' },
      { name: 'Z', type: 'integer', optional: true, desc: 'Number of characters to extract' },
    ],
    returns: 'text',
    since: 'SQLite 3.0',
    examples: ["SELECT SUBSTR('TableNova', 1, 5); -- Returns 'Table'"],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#substr',
  },
  {
    id: 'sqlite:replace',
    name: 'REPLACE',
    engine: 'sqlite',
    category: 'string',
    syntax: 'REPLACE(X, Y, Z)',
    summary: 'Replaces all occurrences of string Y with Z inside X.',
    description: 'Returns a copy of string X in which every occurrence of string Y is replaced with string Z.',
    params: [
      { name: 'X', type: 'text', desc: 'Source string' },
      { name: 'Y', type: 'text', desc: 'Substring to find' },
      { name: 'Z', type: 'text', desc: 'Replacement substring' },
    ],
    returns: 'text',
    since: 'SQLite 3.0.8',
    examples: ["SELECT REPLACE('hello world', 'world', 'TableNova');"],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#replace',
  },
  {
    id: 'sqlite:trim',
    name: 'TRIM',
    engine: 'sqlite',
    category: 'string',
    syntax: 'TRIM(X [, Y])',
    summary: 'Removes leading and trailing spaces (or specified characters Y) from X.',
    description: 'Returns string X with leading and trailing spaces removed. If argument Y is provided, characters contained in Y are trimmed instead.',
    params: [
      { name: 'X', type: 'text', desc: 'Target string' },
      { name: 'Y', type: 'text', optional: true, desc: 'Set of characters to remove' },
    ],
    returns: 'text',
    since: 'SQLite 3.0',
    examples: ["SELECT TRIM('  hello  '); -- Returns 'hello'"],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#trim',
  },

  // --- Math Functions ---
  {
    id: 'sqlite:round',
    name: 'ROUND',
    engine: 'sqlite',
    category: 'math',
    syntax: 'ROUND(X [, Y])',
    summary: 'Rounds X to Y decimal places.',
    description: 'Rounds numeric value X to Y decimal places. If Y is omitted, Y defaults to 0.',
    params: [
      { name: 'X', type: 'numeric', desc: 'Input number' },
      { name: 'Y', type: 'integer', optional: true, desc: 'Decimal places (default 0)' },
    ],
    returns: 'real',
    since: 'SQLite 3.0',
    examples: ['SELECT ROUND(3.14159, 2); -- Returns 3.14'],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#round',
  },
  {
    id: 'sqlite:random',
    name: 'RANDOM',
    engine: 'sqlite',
    category: 'math',
    syntax: 'RANDOM()',
    summary: 'Returns a pseudo-random integer between -9223372036854775808 and +9223372036854775807.',
    description: 'Returns a pseudo-random 64-bit signed integer.',
    params: [],
    returns: 'integer',
    since: 'SQLite 3.0',
    examples: ['SELECT RANDOM();', 'SELECT * FROM users ORDER BY RANDOM() LIMIT 5;'],
    officialUrl: 'https://sqlite.org/lang_corefunc.html#random',
  },

  // --- Date & Time Functions ---
  {
    id: 'sqlite:date',
    name: 'DATE',
    engine: 'sqlite',
    category: 'datetime',
    syntax: 'DATE(timestring, modifier, ...)',
    summary: 'Returns the date in YYYY-MM-DD format.',
    description: 'Returns the date in YYYY-MM-DD format given a time string and optional modifiers.',
    params: [
      { name: 'timestring', type: 'text', desc: "Input timestamp, e.g. 'now'" },
      { name: 'modifier', type: 'text', optional: true, desc: "Modifiers like '+1 day', 'start of month'" },
    ],
    returns: 'text',
    since: 'SQLite 3.0',
    examples: ["SELECT DATE('now');", "SELECT DATE('now', '+1 month', 'start of month');"],
    officialUrl: 'https://sqlite.org/lang_datefunc.html',
  },
  {
    id: 'sqlite:time',
    name: 'TIME',
    engine: 'sqlite',
    category: 'datetime',
    syntax: 'TIME(timestring, modifier, ...)',
    summary: 'Returns the time in HH:MM:SS format.',
    description: 'Returns the time portion of a datetime expression in HH:MM:SS format.',
    params: [
      { name: 'timestring', type: 'text', desc: "Timestamp or 'now'" },
      { name: 'modifier', type: 'text', optional: true, desc: 'Date/time modifiers' },
    ],
    returns: 'text',
    since: 'SQLite 3.0',
    examples: ["SELECT TIME('now');", "SELECT TIME('now', 'localtime');"],
    officialUrl: 'https://sqlite.org/lang_datefunc.html',
  },
  {
    id: 'sqlite:datetime',
    name: 'DATETIME',
    engine: 'sqlite',
    category: 'datetime',
    syntax: 'DATETIME(timestring, modifier, ...)',
    summary: 'Returns date and time in YYYY-MM-DD HH:MM:SS format.',
    description: 'Returns date and time formatted as YYYY-MM-DD HH:MM:SS.',
    params: [
      { name: 'timestring', type: 'text', desc: "Input timestamp or 'now'" },
      { name: 'modifier', type: 'text', optional: true, desc: 'Optional date/time modifiers' },
    ],
    returns: 'text',
    since: 'SQLite 3.0',
    examples: ["SELECT DATETIME('now', 'localtime');"],
    officialUrl: 'https://sqlite.org/lang_datefunc.html',
  },
  {
    id: 'sqlite:strftime',
    name: 'STRFTIME',
    engine: 'sqlite',
    category: 'datetime',
    syntax: 'STRFTIME(format, timestring, modifier, ...)',
    summary: 'Returns date and time formatted according to format string.',
    description: 'Formats a date/time string according to C strftime-like specifiers (%Y, %m, %d, %H, %M, %S, %s, %w, %J).',
    params: [
      { name: 'format', type: 'text', desc: "Format string like '%Y-%m-%d %H:%M'" },
      { name: 'timestring', type: 'text', desc: 'Target timestamp' },
    ],
    returns: 'text',
    since: 'SQLite 3.0',
    examples: ["SELECT STRFTIME('%Y-%m', 'now'); -- Current Year-Month"],
    officialUrl: 'https://sqlite.org/lang_datefunc.html',
  },
  {
    id: 'sqlite:unixepoch',
    name: 'UNIXEPOCH',
    engine: 'sqlite',
    category: 'datetime',
    syntax: 'UNIXEPOCH(timestring, modifier, ...)',
    summary: 'Returns unix timestamp in seconds.',
    description: 'Returns the number of seconds since 1970-01-01 00:00:00 UTC for the given date/time string.',
    params: [{ name: 'timestring', type: 'text', desc: 'Input date string' }],
    returns: 'integer',
    since: 'SQLite 3.38.0',
    examples: ["SELECT UNIXEPOCH('now');"],
    officialUrl: 'https://sqlite.org/lang_datefunc.html',
  },

  // --- Aggregate Functions ---
  {
    id: 'sqlite:count',
    name: 'COUNT',
    engine: 'sqlite',
    category: 'aggregate',
    syntax: 'COUNT(X)',
    summary: 'Returns the number of non-NULL values or rows.',
    description: 'COUNT(X) returns the number of times X is not NULL in a group. COUNT(*) returns total rows in group regardless of NULLs.',
    params: [{ name: 'X', type: 'any', desc: 'Column name or *' }],
    returns: 'integer',
    since: 'SQLite 3.0',
    examples: ['SELECT COUNT(*) FROM users;', 'SELECT COUNT(email) FROM users;'],
    officialUrl: 'https://sqlite.org/lang_aggfunc.html#count',
  },
  {
    id: 'sqlite:sum',
    name: 'SUM',
    engine: 'sqlite',
    category: 'aggregate',
    syntax: 'SUM(X)',
    summary: 'Returns the sum of non-NULL numeric values in group.',
    description: 'Returns the sum of all non-NULL values in the group. If all values are NULL, SUM returns NULL.',
    params: [{ name: 'X', type: 'numeric', desc: 'Numeric column' }],
    returns: 'numeric',
    since: 'SQLite 3.0',
    examples: ['SELECT SUM(amount) FROM orders;'],
    officialUrl: 'https://sqlite.org/lang_aggfunc.html#sum',
  },
  {
    id: 'sqlite:avg',
    name: 'AVG',
    engine: 'sqlite',
    category: 'aggregate',
    syntax: 'AVG(X)',
    summary: 'Returns the average of non-NULL numeric values.',
    description: 'Returns the arithmetic mean of non-NULL values in a group as a floating point number.',
    params: [{ name: 'X', type: 'numeric', desc: 'Numeric column' }],
    returns: 'real',
    since: 'SQLite 3.0',
    examples: ['SELECT AVG(price) FROM products;'],
    officialUrl: 'https://sqlite.org/lang_aggfunc.html#avg',
  },
  {
    id: 'sqlite:group_concat',
    name: 'GROUP_CONCAT',
    engine: 'sqlite',
    category: 'aggregate',
    syntax: 'GROUP_CONCAT(X [, Y])',
    summary: 'Concatenates non-NULL values in a group separated by Y.',
    description: 'Returns a string which is the concatenation of all non-NULL values of X. If Y is specified, it is used as the separator (default is comma ",").',
    params: [
      { name: 'X', type: 'text', desc: 'Column to concatenate' },
      { name: 'Y', type: 'text', optional: true, desc: "Separator string (default ',')" },
    ],
    returns: 'text',
    since: 'SQLite 3.0',
    examples: ["SELECT department_id, GROUP_CONCAT(name, ', ') FROM employees GROUP BY department_id;"],
    officialUrl: 'https://sqlite.org/lang_aggfunc.html#group_concat',
  },

  // --- JSON / JSONB Functions (SQLite 3.38+ / 3.45+ JSONB) ---
  {
    id: 'sqlite:json_extract',
    name: 'JSON_EXTRACT',
    engine: 'sqlite',
    category: 'json',
    syntax: 'JSON_EXTRACT(json, path, ...)',
    summary: 'Extracts values from JSON document matching JSON path.',
    description: 'Extracts values from JSON string or JSONB object specified by path parameters. Paths start with $.',
    params: [
      { name: 'json', type: 'json | text | jsonb', desc: 'JSON document' },
      { name: 'path', type: 'text', desc: "Path string like '$.user.id' or '$[0]'" },
    ],
    returns: 'any',
    since: 'SQLite 3.9.0 / 3.45.0',
    examples: ["SELECT JSON_EXTRACT(data, '$.name') FROM logs;"],
    officialUrl: 'https://sqlite.org/json1.html#jex',
  },
  {
    id: 'sqlite:json_object',
    name: 'JSON_OBJECT',
    engine: 'sqlite',
    category: 'json',
    syntax: 'JSON_OBJECT(key1, val1, key2, val2, ...)',
    summary: 'Constructs a JSON object from key/value pairs.',
    description: 'Constructs a JSON object from alternating key and value arguments.',
    params: [
      { name: 'key', type: 'text', desc: 'Object key name' },
      { name: 'value', type: 'any', desc: 'Object property value' },
    ],
    returns: 'json',
    since: 'SQLite 3.9.0',
    examples: ["SELECT JSON_OBJECT('id', id, 'name', name) FROM users;"],
    officialUrl: 'https://sqlite.org/json1.html#jobj',
  },
  {
    id: 'sqlite:json_array',
    name: 'JSON_ARRAY',
    engine: 'sqlite',
    category: 'json',
    syntax: 'JSON_ARRAY(val1, val2, ...)',
    summary: 'Constructs a JSON array from arguments.',
    description: 'Constructs a JSON array containing all arguments as array elements.',
    params: [{ name: '...', type: 'any', desc: 'Values to place into JSON array' }],
    returns: 'json',
    since: 'SQLite 3.9.0',
    examples: ["SELECT JSON_ARRAY(1, 2, 'three', NULL);"],
    officialUrl: 'https://sqlite.org/json1.html#jarray',
  },
  {
    id: 'sqlite:jsonb',
    name: 'JSONB',
    engine: 'sqlite',
    category: 'json',
    syntax: 'JSONB(json)',
    summary: 'Converts JSON text to SQLite binary JSONB format.',
    description: 'Converts JSON text string into SQLite binary JSONB internal representation for faster extraction and lower memory overhead (SQLite 3.45.0+).',
    params: [{ name: 'json', type: 'text', desc: 'Valid JSON text string' }],
    returns: 'blob',
    since: 'SQLite 3.45.0',
    examples: ["SELECT JSONB('{\"a\":1, \"b\":2}');"],
    officialUrl: 'https://sqlite.org/json1.html#jsonb',
  },

  // --- Window Functions ---
  {
    id: 'sqlite:row_number',
    name: 'ROW_NUMBER',
    engine: 'sqlite',
    category: 'window',
    syntax: 'ROW_NUMBER() OVER ([PARTITION BY ...] ORDER BY ...)',
    summary: 'Assigns a unique 1-based sequential integer to each row in partition.',
    description: 'Returns the 1-based index of the row within its window partition.',
    params: [],
    returns: 'integer',
    since: 'SQLite 3.25.0',
    examples: ['SELECT name, department, ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) FROM employees;'],
    officialUrl: 'https://sqlite.org/windowfunctions.html',
  },
  {
    id: 'sqlite:rank',
    name: 'RANK',
    engine: 'sqlite',
    category: 'window',
    syntax: 'RANK() OVER ([PARTITION BY ...] ORDER BY ...)',
    summary: 'Returns rank of current row with gaps for ties.',
    description: 'Returns the rank of the current row within its partition. Ties produce identical rank values, creating gaps in numbers.',
    params: [],
    returns: 'integer',
    since: 'SQLite 3.25.0',
    examples: ['SELECT score, RANK() OVER (ORDER BY score DESC) FROM leaderboard;'],
    officialUrl: 'https://sqlite.org/windowfunctions.html',
  },

  // --- SQLite Pragmas ---
  {
    id: 'sqlite:pragma_foreign_keys',
    name: 'PRAGMA foreign_keys',
    engine: 'sqlite',
    category: 'pragma',
    syntax: 'PRAGMA foreign_keys = ON | OFF;',
    summary: 'Enables or disables foreign key enforcement.',
    description: 'Queries, enables or disables enforcement of foreign key constraints in the current SQLite database connection.',
    params: [{ name: 'state', type: 'ON | OFF', desc: 'Enable or disable foreign key checks' }],
    since: 'SQLite 3.6.19',
    examples: ['PRAGMA foreign_keys = ON;', 'PRAGMA foreign_keys;'],
    officialUrl: 'https://sqlite.org/pragma.html#pragma_foreign_keys',
  },
  {
    id: 'sqlite:pragma_table_info',
    name: 'PRAGMA table_info',
    engine: 'sqlite',
    category: 'pragma',
    syntax: 'PRAGMA table_info(table_name);',
    summary: 'Returns table column schema details.',
    description: 'Returns one row for each column in the named table, listing column ID, name, data type, NOT NULL flag, default value, and primary key index.',
    params: [{ name: 'table_name', type: 'text', desc: 'Name of target table' }],
    since: 'SQLite 3.0',
    examples: ["PRAGMA table_info('users');"],
    officialUrl: 'https://sqlite.org/pragma.html#pragma_table_info',
  },
  {
    id: 'sqlite:pragma_journal_mode',
    name: 'PRAGMA journal_mode',
    engine: 'sqlite',
    category: 'pragma',
    syntax: 'PRAGMA journal_mode = DELETE | TRUNCATE | PERSIST | MEMORY | WAL | OFF;',
    summary: 'Queries or sets database journal mode.',
    description: 'Sets or queries the transaction rollback journal mode. WAL (Write-Ahead Logging) offers high concurrency.',
    params: [{ name: 'mode', type: 'WAL | DELETE | ...', desc: 'Target journal mode' }],
    since: 'SQLite 3.7.0',
    examples: ['PRAGMA journal_mode = WAL;'],
    officialUrl: 'https://sqlite.org/pragma.html#pragma_journal_mode',
  },
];
