import React, { useState, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { useTranslation } from 'react-i18next';
import {
  Search, Plus, X, Info, Check, Copy, Trash2, ChevronDown, Sparkles, BookOpen, ExternalLink
} from 'lucide-react';
import { searchDocs, getDocSummary, getDocDescription, getParamDesc, normalizeEngine } from '../utils/docsService';
import type { DocEntry } from '../docsData/types';

export interface SqlSnippet {
  id: string;
  name: string;
  category: 'DML' | 'DDL' | 'Flow Control' | 'Aggregate' | 'Comment' | 'Custom';
  description: string;
  template: string;
  isCustom?: boolean;
  docEntry?: DocEntry;
}

const DEFAULT_SNIPPETS: SqlSnippet[] = [
  {
    id: 'select_syntax',
    name: 'SELECT Syntax',
    category: 'DML',
    description: 'Retrieve rows selected from one or more tables',
    template: `SELECT column1, column2\nFROM table_name\nWHERE condition;`,
  },
  {
    id: 'insert_syntax',
    name: 'INSERT Syntax',
    category: 'DML',
    description: 'Insert new rows into an existing table',
    template: `INSERT INTO table_name (column1, column2)\nVALUES (value1, value2);`,
  },
  {
    id: 'update_syntax',
    name: 'UPDATE Syntax',
    category: 'DML',
    description: 'Updates columns of existing rows in the named table',
    template: `UPDATE table_name\nSET column1 = value1, column2 = value2\nWHERE condition;`,
  },
  {
    id: 'delete_syntax',
    name: 'DELETE Syntax',
    category: 'DML',
    description: 'Deletes existing rows from a table',
    template: `DELETE FROM table_name\nWHERE condition;`,
  },
  {
    id: 'case_flow',
    name: 'CASE',
    category: 'Flow Control',
    description: 'Create a conditional construct',
    template: `CASE\n    WHEN condition1 THEN result1\n    WHEN condition2 THEN result2\n    ELSE default_result\nEND`,
  },
  {
    id: 'comments',
    name: 'COMMENTS',
    category: 'Comment',
    description: 'Create a comment in SQL script',
    template: `/* Multi-line comment\n   Block text here */\n-- Single line comment`,
  },
  {
    id: 'customize_tab_name',
    name: 'Customize Result Tab Name',
    category: 'Comment',
    description: 'To name the result tab generated by executing the statement.',
    template: `-- @name: ResultTabName\nSELECT * FROM table_name;`,
  },
  {
    id: 'if_else_flow',
    name: 'IF...ELSE...',
    category: 'Flow Control',
    description: 'Create a IF...ELSE... construct',
    template: `IF condition THEN\n    -- statements\nELSE\n    -- statements\nEND IF;`,
  },
  {
    id: 'loop_flow',
    name: 'LOOP',
    category: 'Flow Control',
    description: 'Create a simple loop construct',
    template: `LOOP\n    -- statements\n    LEAVE loop_label;\nEND LOOP;`,
  },
  {
    id: 'repeat_flow',
    name: 'REPEAT',
    category: 'Flow Control',
    description: 'Create A REPEAT construct. The Statement list is repeated until the search_condition expression is true.',
    template: `REPEAT\n    -- statements\nUNTIL search_condition\nEND REPEAT;`,
  },
  {
    id: 'runtime_parameter',
    name: 'Runtime Parameter',
    category: 'DML',
    description: 'Runtime parameter to be replaced when the statements are executed.',
    template: `SELECT * FROM table_name WHERE id = :param_id;`,
  },
  {
    id: 'while_flow',
    name: 'WHILE',
    category: 'Flow Control',
    description: 'Create a WHILE construct. The statement list within a WHILE statement is repeated as long as condition is true.',
    template: `WHILE condition DO\n    -- statements\nEND WHILE;`,
  },
  {
    id: 'join_clause',
    name: 'JOIN Clause',
    category: 'DML',
    description: 'Combine rows from two or more tables based on a related column',
    template: `SELECT t1.column1, t2.column2\nFROM table1 t1\nINNER JOIN table2 t2 ON t1.id = t2.table1_id;`,
  },
  {
    id: 'group_by_having',
    name: 'GROUP BY & HAVING',
    category: 'Aggregate',
    description: 'Group rows that have the same values and filter groups',
    template: `SELECT column_name, COUNT(*)\nFROM table_name\nGROUP BY column_name\nHAVING COUNT(*) > 1;`,
  },
  {
    id: 'create_table',
    name: 'CREATE TABLE',
    category: 'DDL',
    description: 'Create a new table in the database',
    template: `CREATE TABLE table_name (\n    id INT PRIMARY KEY AUTO_INCREMENT,\n    name VARCHAR(255) NOT NULL,\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);`,
  },
  {
    id: 'alter_table',
    name: 'ALTER TABLE',
    category: 'DDL',
    description: 'Add, delete, or modify columns in an existing table',
    template: `ALTER TABLE table_name\nADD COLUMN new_column VARCHAR(100);`,
  },
  {
    id: 'create_index',
    name: 'CREATE INDEX',
    category: 'DDL',
    description: 'Create an index on a table to speed up queries',
    template: `CREATE INDEX idx_column_name\nON table_name (column_name);`,
  },
];

const LOCAL_STORAGE_CUSTOM_KEY = 'tablenova.sql_custom_snippets';

interface SqlSnippetPanelProps {
  dbType?: string;
  onInsertSnippet: (template: string) => void;
  onClose: () => void;
}

export const SqlSnippetPanel: React.FC<SqlSnippetPanelProps> = ({ dbType, onInsertSnippet, onClose }) => {
  const { i18n } = useTranslation();
  const [customSnippets, setCustomSnippets] = useState<SqlSnippet[]>(() => {
    try {
      const stored = typeof localStorage !== 'undefined' ? localStorage.getItem(LOCAL_STORAGE_CUSTOM_KEY) : null;
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  });
  const [selectedCategory, setSelectedCategory] = useState<string>('All Labels');
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Doc Detail Modal State
  const [selectedDoc, setSelectedDoc] = useState<DocEntry | null>(null);

  // Modal Add New Custom Snippet State
  const [showAddModal, setShowAddModal] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newCategory, setNewCategory] = useState<'DML' | 'DDL' | 'Flow Control' | 'Aggregate' | 'Comment' | 'Custom'>('Custom');
  const [newDesc, setNewDesc] = useState('');
  const [newTemplate, setNewTemplate] = useState('');

  // Leverage docsService to generate engine-specific snippets automatically
  const engineDocs = useMemo(() => {
    const targetEngine = normalizeEngine(dbType) || 'all';
    const docs = searchDocs({ engine: targetEngine as any });
    return docs.map((doc): SqlSnippet => {
      const categoryMap: Record<string, SqlSnippet['category']> = {
        dml: 'DML',
        ddl: 'DDL',
        control_flow: 'Flow Control',
        aggregate: 'Aggregate',
        window: 'Aggregate',
        transaction: 'DML',
        string: 'DML',
        datetime: 'DML',
        json: 'DML',
        math: 'Aggregate',
        command: 'DML',
        pragma: 'DDL',
      };

      const template = doc.examples && doc.examples.length > 0 ? doc.examples[0] : doc.syntax;
      const description = getDocSummary(doc, i18n.language);

      return {
        id: `doc_${doc.id}`,
        name: doc.name,
        category: categoryMap[doc.category] || 'DML',
        description,
        template,
        docEntry: doc,
      };
    });
  }, [dbType, i18n.language]);

  const allSnippets = useMemo(() => {
    return [...DEFAULT_SNIPPETS, ...engineDocs, ...customSnippets];
  }, [engineDocs, customSnippets]);

  const saveCustomSnippets = (updated: SqlSnippet[]) => {
    setCustomSnippets(updated);
    try {
      localStorage.setItem(LOCAL_STORAGE_CUSTOM_KEY, JSON.stringify(updated));
    } catch (e) {
      console.error('Failed to save custom snippets:', e);
    }
  };

  const handleAddSnippet = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim() || !newTemplate.trim()) return;

    const newSnippet: SqlSnippet = {
      id: `custom_${Date.now()}`,
      name: newTitle.trim(),
      category: newCategory,
      description: newDesc.trim() || 'Custom user SQL snippet',
      template: newTemplate,
      isCustom: true,
    };

    saveCustomSnippets([...customSnippets, newSnippet]);
    setShowAddModal(false);
    setNewTitle('');
    setNewDesc('');
    setNewTemplate('');
  };

  const handleDeleteCustomSnippet = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const updated = customSnippets.filter(s => s.id !== id);
    saveCustomSnippets(updated);
  };

  const handleCopySnippet = (sn: SqlSnippet, e: React.MouseEvent) => {
    e.stopPropagation();
    navigator.clipboard.writeText(sn.template);
    setCopiedId(sn.id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const filteredSnippets = allSnippets.filter(sn => {
    const matchesCategory = selectedCategory === 'All Labels' || sn.category === selectedCategory;
    const q = searchQuery.toLowerCase();
    const matchesSearch = !q ||
      sn.name.toLowerCase().includes(q) ||
      sn.description.toLowerCase().includes(q) ||
      sn.category.toLowerCase().includes(q) ||
      sn.template.toLowerCase().includes(q);
    return matchesCategory && matchesSearch;
  });

  return (
    <div
      style={{
        width: '290px',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        background: 'var(--win-bg-window)',
        borderLeft: '1px solid var(--win-border)',
        boxSizing: 'border-box',
        fontSize: '12px',
        userSelect: 'none',
        flexShrink: 0,
        position: 'relative',
        zIndex: 5,
      }}
    >
      {/* Top Header Bar */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '8px 12px',
          borderBottom: '1px solid var(--win-border-light, var(--win-border))',
          background: 'var(--win-bg-card)',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <button
            onClick={() => {
              if (engineDocs.length > 0) {
                setSelectedDoc(engineDocs[0].docEntry || null);
              }
            }}
            title="Xem tài liệu hướng dẫn SQL (DocsViewer)"
            style={{
              background: 'transparent',
              border: 'none',
              color: 'var(--win-text-secondary)',
              cursor: 'pointer',
              padding: 0,
              display: 'flex',
              alignItems: 'center',
            }}
          >
            <Info size={15} />
          </button>

          {/* Icon Parentheses / Snippet (Active Accent) */}
          <div
            title="SQL Snippets Library"
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'var(--win-accent, #3b82f6)',
              fontWeight: 700,
              fontSize: '14px',
              cursor: 'default',
            }}
          >
            ()
          </div>
        </div>

        <button
          onClick={onClose}
          title="Đóng panel Snippet"
          style={{
            background: 'transparent',
            border: 'none',
            color: 'var(--win-text-secondary)',
            cursor: 'pointer',
            padding: '2px',
            borderRadius: '4px',
            display: 'flex',
            alignItems: 'center',
          }}
        >
          <X size={15} />
        </button>
      </div>

      {/* Category Dropdown & Add Button */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '8px',
          padding: '8px 12px',
          borderBottom: '1px solid var(--win-border)',
          background: 'var(--win-bg-window)',
        }}
      >
        <div style={{ position: 'relative', flex: 1 }}>
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            style={{
              width: '100%',
              padding: '4px 24px 4px 8px',
              fontSize: '12px',
              borderRadius: '4px',
              border: '1px solid var(--win-border)',
              background: 'var(--win-bg-card)',
              color: 'var(--win-text-primary)',
              appearance: 'none',
              cursor: 'pointer',
              outline: 'none',
            }}
          >
            <option value="All Labels">All Labels</option>
            <option value="DML">DML</option>
            <option value="DDL">DDL</option>
            <option value="Flow Control">Flow Control</option>
            <option value="Aggregate">Aggregate</option>
            <option value="Comment">Comment</option>
            <option value="Custom">Custom</option>
          </select>
          <ChevronDown
            size={13}
            style={{
              position: 'absolute',
              right: '6px',
              top: '50%',
              transform: 'translateY(-50%)',
              pointerEvents: 'none',
              color: 'var(--win-text-secondary)',
            }}
          />
        </div>

        <button
          onClick={() => setShowAddModal(true)}
          title="Thêm snippet mới"
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '24px',
            height: '24px',
            borderRadius: '4px',
            border: '1px solid var(--win-border)',
            background: 'var(--win-bg-card)',
            color: '#10b981',
            cursor: 'pointer',
            flexShrink: 0,
          }}
        >
          <Plus size={14} />
        </button>
      </div>

      {/* Snippet List Container */}
      <div
        style={{
          flex: 1,
          overflowY: 'auto',
          padding: '4px 0',
        }}
      >
        {filteredSnippets.length === 0 ? (
          <div style={{ padding: '24px 16px', textAlign: 'center', color: 'var(--win-text-disabled)', fontSize: '11.5px' }}>
            Không tìm thấy mẫu SQL nào
          </div>
        ) : (
          filteredSnippets.map((sn) => (
            <div
              key={sn.id}
              onClick={() => onInsertSnippet(sn.template)}
              onDoubleClick={() => onInsertSnippet(sn.template)}
              title="Bấm hoặc nhấp kép để chèn vào Editor"
              style={{
                display: 'flex',
                alignItems: 'flex-start',
                gap: '10px',
                padding: '8px 12px',
                borderBottom: '1px solid var(--win-border-light, rgba(229,231,235,0.2))',
                cursor: 'pointer',
                transition: 'background 0.12s ease',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = 'var(--win-bg-hover, rgba(0, 102, 204, 0.08))';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = 'transparent';
              }}
            >
              {/* Document Icon with Code Brackets */}
              <div
                style={{
                  width: '24px',
                  height: '28px',
                  borderRadius: '4px',
                  border: '1px solid #93c5fd',
                  background: '#eff6ff',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  color: '#10b981',
                  fontWeight: 700,
                  fontSize: '11px',
                  flexShrink: 0,
                  marginTop: '2px',
                }}
              >
                ()
              </div>

              {/* Snippet Details */}
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}>
                  <span style={{ fontWeight: 700, color: 'var(--win-text-primary)', fontSize: '12px' }}>
                    {sn.name}
                  </span>
                  <span style={{ fontSize: '10px', color: 'var(--win-text-disabled)' }}>
                    {sn.category}
                  </span>
                </div>

                <div
                  style={{
                    fontSize: '11px',
                    color: 'var(--win-text-secondary)',
                    marginTop: '2px',
                    lineHeight: 1.3,
                    display: '-webkit-box',
                    WebkitLineClamp: 2,
                    WebkitBoxOrient: 'vertical',
                    overflow: 'hidden',
                  }}
                >
                  {sn.description}
                </div>
              </div>

              {/* Action Buttons (Doc Info / Copy / Delete) */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '4px', opacity: 0.8 }}>
                {sn.docEntry && (
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      setSelectedDoc(sn.docEntry || null);
                    }}
                    title="Xem chi tiết hướng dẫn & cú pháp"
                    style={{
                      background: 'transparent',
                      border: 'none',
                      color: 'var(--win-accent, #3b82f6)',
                      cursor: 'pointer',
                      padding: '2px',
                    }}
                  >
                    <BookOpen size={13} />
                  </button>
                )}
                <button
                  onClick={(e) => handleCopySnippet(sn, e)}
                  title="Sao chép SQL snippet"
                  style={{
                    background: 'transparent',
                    border: 'none',
                    color: copiedId === sn.id ? '#10b981' : 'var(--win-text-disabled)',
                    cursor: 'pointer',
                    padding: '2px',
                  }}
                >
                  {copiedId === sn.id ? <Check size={13} /> : <Copy size={13} />}
                </button>
                {sn.isCustom && (
                  <button
                    onClick={(e) => handleDeleteCustomSnippet(sn.id, e)}
                    title="Xoá snippet tuỳ chỉnh"
                    style={{
                      background: 'transparent',
                      border: 'none',
                      color: '#ef4444',
                      cursor: 'pointer',
                      padding: '2px',
                    }}
                  >
                    <Trash2 size={13} />
                  </button>
                )}
              </div>
            </div>
          ))
        )}
      </div>

      {/* Bottom Search Bar */}
      <div
        style={{
          padding: '8px 12px',
          borderTop: '1px solid var(--win-border)',
          background: 'var(--win-bg-card)',
        }}
      >
        <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
          <Search
            size={13}
            style={{
              position: 'absolute',
              left: '8px',
              color: 'var(--win-text-disabled)',
              pointerEvents: 'none',
            }}
          />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search"
            style={{
              width: '100%',
              padding: '4px 8px 4px 26px',
              fontSize: '11.5px',
              borderRadius: '4px',
              border: '1px solid var(--win-border)',
              background: 'var(--win-bg-window)',
              color: 'var(--win-text-primary)',
              outline: 'none',
            }}
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              style={{
                position: 'absolute',
                right: '6px',
                background: 'transparent',
                border: 'none',
                color: 'var(--win-text-disabled)',
                cursor: 'pointer',
                padding: 0,
                display: 'flex',
                alignItems: 'center',
              }}
            >
              <X size={12} />
            </button>
          )}
        </div>
      </div>

      {/* Modal View Documentation Detail (DocsViewer) */}
      {selectedDoc && createPortal(
        <div
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0, 0, 0, 0.55)',
            backdropFilter: 'blur(3px)',
            zIndex: 10000,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <div
            style={{
              width: '580px',
              maxWidth: '90vw',
              maxHeight: '85vh',
              background: 'var(--win-bg-card)',
              border: '1px solid var(--win-border-strong, var(--win-border))',
              borderRadius: '10px',
              boxShadow: '0 20px 48px rgba(0,0,0,0.5)',
              padding: '20px 24px',
              display: 'flex',
              flexDirection: 'column',
              gap: '14px',
              overflow: 'hidden',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--win-border)', paddingBottom: '10px' }}>
              <div style={{ fontWeight: 700, fontSize: '15px', color: 'var(--win-text-primary)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <BookOpen size={18} style={{ color: 'var(--win-accent)' }} />
                <span>{selectedDoc.name}</span>
                <span style={{ fontSize: '11.5px', color: 'var(--win-text-disabled)', fontWeight: 400 }}>({selectedDoc.engine.toUpperCase()})</span>
              </div>
              <button
                onClick={() => setSelectedDoc(null)}
                style={{ background: 'transparent', border: 'none', color: 'var(--win-text-secondary)', cursor: 'pointer', padding: '4px' }}
              >
                <X size={16} />
              </button>
            </div>

            <div style={{ overflowY: 'auto', flex: 1, display: 'flex', flexDirection: 'column', gap: '14px', paddingRight: '4px' }}>
              {/* Syntax */}
              <div>
                <div style={{ fontSize: '11px', fontWeight: 600, color: 'var(--win-text-disabled)', textTransform: 'uppercase', marginBottom: '6px' }}>Cú pháp Syntax</div>
                <div style={{ padding: '10px 12px', background: 'var(--win-bg-window)', border: '1px solid var(--win-border)', borderRadius: '6px', fontFamily: 'Consolas, Monaco, monospace', fontSize: '12.5px', color: 'var(--win-accent)' }}>
                  {selectedDoc.syntax}
                </div>
              </div>

              {/* Description */}
              <div>
                <div style={{ fontSize: '11px', fontWeight: 600, color: 'var(--win-text-disabled)', textTransform: 'uppercase', marginBottom: '6px' }}>Mô tả chi tiết</div>
                <div style={{ fontSize: '12.5px', color: 'var(--win-text-primary)', lineHeight: 1.5 }}>
                  {getDocDescription(selectedDoc, i18n.language)}
                </div>
              </div>

              {/* Parameters if present */}
              {selectedDoc.params && selectedDoc.params.length > 0 && (
                <div>
                  <div style={{ fontSize: '11px', fontWeight: 600, color: 'var(--win-text-disabled)', textTransform: 'uppercase', marginBottom: '6px' }}>Tham số (Parameters)</div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                    {selectedDoc.params.map((p, idx) => (
                      <div key={idx} style={{ fontSize: '12px', background: 'var(--win-bg-window)', padding: '6px 10px', borderRadius: '6px', border: '1px solid var(--win-border)' }}>
                        <strong style={{ color: 'var(--win-text-primary)' }}>{p.name}</strong>
                        {p.type && <span style={{ color: 'var(--win-text-disabled)', marginLeft: '4px' }}>({p.type})</span>}:{' '}
                        <span style={{ color: 'var(--win-text-secondary)' }}>{getParamDesc(p, i18n.language)}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Examples */}
              {selectedDoc.examples && selectedDoc.examples.length > 0 && (
                <div>
                  <div style={{ fontSize: '11px', fontWeight: 600, color: 'var(--win-text-disabled)', textTransform: 'uppercase', marginBottom: '6px' }}>Ví dụ minh họa (Example Code)</div>
                  {selectedDoc.examples.map((ex, idx) => (
                    <div key={idx} style={{ position: 'relative', marginBottom: '8px' }}>
                      <pre style={{ margin: 0, padding: '10px 12px', background: 'var(--win-bg-window)', border: '1px solid var(--win-border)', borderRadius: '6px', fontFamily: 'Consolas, Monaco, monospace', fontSize: '12px', color: 'var(--win-text-primary)', whiteSpace: 'pre-wrap' }}>
                        {ex}
                      </pre>
                      <button
                        onClick={() => {
                          onInsertSnippet(ex);
                          setSelectedDoc(null);
                        }}
                        style={{
                          position: 'absolute',
                          top: '6px',
                          right: '6px',
                          padding: '3px 10px',
                          fontSize: '11px',
                          borderRadius: '4px',
                          border: '1px solid var(--win-border)',
                          background: 'var(--win-bg-card)',
                          color: 'var(--win-accent)',
                          cursor: 'pointer',
                          fontWeight: 600,
                        }}
                      >
                        Chèn ví dụ này
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid var(--win-border)', paddingTop: '10px' }}>
              {selectedDoc.officialUrl ? (
                <a
                  href={selectedDoc.officialUrl}
                  target="_blank"
                  rel="noreferrer"
                  style={{ fontSize: '12px', color: 'var(--win-accent)', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '4px' }}
                >
                  <span>Tài liệu chính thức</span>
                  <ExternalLink size={13} />
                </a>
              ) : <div />}

              <div style={{ display: 'flex', gap: '10px' }}>
                <button
                  className="btn btn-secondary"
                  onClick={() => setSelectedDoc(null)}
                  style={{ padding: '6px 16px', fontSize: '12px' }}
                >
                  Đóng
                </button>
                <button
                  className="btn btn-primary"
                  onClick={() => {
                    const snippetCode = selectedDoc.examples && selectedDoc.examples.length > 0 ? selectedDoc.examples[0] : selectedDoc.syntax;
                    onInsertSnippet(snippetCode);
                    setSelectedDoc(null);
                  }}
                  style={{ padding: '6px 18px', fontSize: '12px' }}
                >
                  Chèn vào SQL Editor
                </button>
              </div>
            </div>
          </div>
        </div>,
        document.body
      )}

      {/* Modal Add Custom Snippet */}
      {showAddModal && createPortal(
        <div
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0, 0, 0, 0.55)',
            backdropFilter: 'blur(3px)',
            zIndex: 10000,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <div
            style={{
              width: '540px',
              maxWidth: '90vw',
              background: 'var(--win-bg-card)',
              border: '1px solid var(--win-border-strong, var(--win-border))',
              borderRadius: '10px',
              boxShadow: '0 20px 48px rgba(0,0,0,0.5)',
              padding: '20px 24px',
              display: 'flex',
              flexDirection: 'column',
              gap: '16px',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--win-border)', paddingBottom: '12px' }}>
              <div style={{ fontWeight: 700, fontSize: '15px', color: 'var(--win-text-primary)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Sparkles size={16} style={{ color: 'var(--win-accent)' }} />
                <span>Thêm Mẫu SQL Snippet Mới</span>
              </div>
              <button
                onClick={() => setShowAddModal(false)}
                style={{ background: 'transparent', border: 'none', color: 'var(--win-text-secondary)', cursor: 'pointer', padding: '4px' }}
              >
                <X size={16} />
              </button>
            </div>

            <form onSubmit={handleAddSnippet} style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 140px', gap: '12px' }}>
                <div>
                  <label style={{ fontSize: '11.5px', fontWeight: 600, color: 'var(--win-text-secondary)', display: 'block', marginBottom: '6px' }}>
                    Tên Snippet *
                  </label>
                  <input
                    type="text"
                    required
                    value={newTitle}
                    onChange={(e) => setNewTitle(e.target.value)}
                    placeholder="Ví dụ: SELECT TOP 100"
                    style={{
                      width: '100%',
                      padding: '7px 10px',
                      fontSize: '12.5px',
                      borderRadius: '6px',
                      border: '1px solid var(--win-border)',
                      background: 'var(--win-bg-window)',
                      color: 'var(--win-text-primary)',
                      boxSizing: 'border-box',
                      outline: 'none',
                    }}
                  />
                </div>

                <div>
                  <label style={{ fontSize: '11.5px', fontWeight: 600, color: 'var(--win-text-secondary)', display: 'block', marginBottom: '6px' }}>
                    Phân loại
                  </label>
                  <select
                    value={newCategory}
                    onChange={(e) => setNewCategory(e.target.value as any)}
                    style={{
                      width: '100%',
                      padding: '7px 10px',
                      fontSize: '12.5px',
                      borderRadius: '6px',
                      border: '1px solid var(--win-border)',
                      background: 'var(--win-bg-window)',
                      color: 'var(--win-text-primary)',
                      boxSizing: 'border-box',
                      outline: 'none',
                    }}
                  >
                    <option value="Custom">Custom</option>
                    <option value="DML">DML</option>
                    <option value="DDL">DDL</option>
                    <option value="Flow Control">Flow Control</option>
                    <option value="Aggregate">Aggregate</option>
                    <option value="Comment">Comment</option>
                  </select>
                </div>
              </div>

              <div>
                <label style={{ fontSize: '11.5px', fontWeight: 600, color: 'var(--win-text-secondary)', display: 'block', marginBottom: '6px' }}>
                  Mô tả
                </label>
                <input
                  type="text"
                  value={newDesc}
                  onChange={(e) => setNewDesc(e.target.value)}
                  placeholder="Mô tả ngắn gọn công dụng mẫu SQL"
                  style={{
                    width: '100%',
                    padding: '7px 10px',
                    fontSize: '12.5px',
                    borderRadius: '6px',
                    border: '1px solid var(--win-border)',
                    background: 'var(--win-bg-window)',
                    color: 'var(--win-text-primary)',
                    boxSizing: 'border-box',
                    outline: 'none',
                  }}
                />
              </div>

              <div>
                <label style={{ fontSize: '11.5px', fontWeight: 600, color: 'var(--win-text-secondary)', display: 'block', marginBottom: '6px' }}>
                  Nội dung SQL Template *
                </label>
                <textarea
                  required
                  rows={7}
                  value={newTemplate}
                  onChange={(e) => setNewTemplate(e.target.value)}
                  placeholder={`SELECT * FROM my_table WHERE status = 'active';`}
                  style={{
                    width: '100%',
                    padding: '10px',
                    fontSize: '12.5px',
                    fontFamily: 'Consolas, Monaco, "Courier New", monospace',
                    lineHeight: 1.5,
                    borderRadius: '6px',
                    border: '1px solid var(--win-border)',
                    background: 'var(--win-bg-window)',
                    color: 'var(--win-text-primary)',
                    boxSizing: 'border-box',
                    resize: 'vertical',
                    minHeight: '140px',
                    outline: 'none',
                  }}
                />
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '6px' }}>
                <button
                  type="button"
                  className="btn btn-secondary"
                  onClick={() => setShowAddModal(false)}
                  style={{ padding: '6px 16px', fontSize: '12px' }}
                >
                  Hủy
                </button>
                <button
                  type="submit"
                  className="btn btn-primary"
                  style={{ padding: '6px 20px', fontSize: '12px' }}
                >
                  Lưu Snippet
                </button>
              </div>
            </form>
          </div>
        </div>,
        document.body
      )}
    </div>
  );
};
